export const PHRASES = [
  { it: "Buongiorno!", en: "Good morning!" },
  { it: "Buonasera!", en: "Good evening!" },
  { it: "Buonanotte!", en: "Good night!" },
  { it: "Ciao!", en: "Hi!/Bye!" },
  { it: "A dopo!", en: "See you later!" },
  { it: "A domani!", en: "See you tomorrow!" },
  { it: "A presto!", en: "See you soon!" },
  { it: "Come va?", en: "How’s it going?" },
  { it: "Come stai?", en: "How are you?" },
  { it: "Tutto bene.", en: "All good." },
  { it: "Non c’è male.", en: "Not bad." },
  { it: "Grazie!", en: "Thanks!" },
  { it: "Grazie mille.", en: "Thanks a lot." },
  { it: "Prego.", en: "You’re welcome." },
  { it: "Per favore.", en: "Please." },
  { it: "Scusa.", en: "Sorry/Excuse me." },
  { it: "Mi dispiace.", en: "I’m sorry." },
  { it: "Nessun problema.", en: "No problem." },
  { it: "Tranquillo.", en: "Don’t worry." },
  { it: "Un momento.", en: "One moment." },
  { it: "Arrivo subito.", en: "Be right there." },
  { it: "Sto arrivando.", en: "I’m on my way." },
  { it: "Sono in ritardo.", en: "I’m late." },
  { it: "Dove sei?", en: "Where are you?" },
  { it: "Dove ci vediamo?", en: "Where do we meet?" },
  { it: "A che ora?", en: "What time?" },
  { it: "Che ore sono?", en: "What time is it?" },
  { it: "Andiamo!", en: "Let’s go!" },
  { it: "Aspetta!", en: "Wait!" },
  { it: "Capito.", en: "Got it." },
  { it: "Non capisco.", en: "I don’t understand." },
  { it: "Puoi ripetere?", en: "Can you repeat?" },
  { it: "Parli inglese?", en: "Do you speak English?" },
  { it: "Dove si trova il bagno?", en: "Where is the bathroom?" },
  { it: "Quanto costa?", en: "How much is it?" },
  { it: "Va bene.", en: "All right/Okay." },
  { it: "Certo.", en: "Sure." },
  { it: "Perfetto.", en: "Perfect." },
  { it: "Forse.", en: "Maybe." },
  { it: "Non lo so.", en: "I don’t know." },
  { it: "Un caffè, per favore.", en: "A coffee, please." },
  { it: "Ho fame.", en: "I’m hungry." },
  { it: "Ho sete.", en: "I’m thirsty." },
  { it: "Buona giornata!", en: "Have a nice day!" },
  { it: "Buon weekend!", en: "Have a nice weekend!" },
  { it: "Buon lavoro!", en: "Have a good workday!" },
  { it: "In bocca al lupo!", en: "Good luck!" },
  { it: "Complimenti!", en: "Congrats!" },
  { it: "Ben fatto!", en: "Well done!" },
  { it: "Funziona.", en: "It works." },
  { it: "Non funziona.", en: "It doesn’t work." },
  { it: "Va tutto bene.", en: "Everything’s okay." },
  { it: "Che bello!", en: "How nice!" },
  { it: "Che peccato.", en: "What a pity." },
  { it: "Ti va?", en: "Feel like it?" },
  { it: "Volentieri.", en: "I’d love to." },
  { it: "Magari.", en: "Maybe/I’d love that." },
  { it: "Ti scrivo.", en: "I’ll text you." },
  { it: "Ti chiamo.", en: "I’ll call you." },
  { it: "Ci sentiamo.", en: "Talk soon." },
  { it: "Fatti sentire.", en: "Keep in touch." },
  { it: "Buon appetito!", en: "Enjoy your meal!" },
  { it: "Salute!", en: "Cheers/Bless you!" },
  { it: "Attento!", en: "Watch out!" },
  { it: "Dai!", en: "Come on!" },
  { it: "Figurati.", en: "Don’t mention it." }
];

let lastIdx = -1;
export function randomPhraseNoRepeat() {
  if (PHRASES.length === 0) return { it: "Ciao!", en: "Hi!" };
  let idx;
  do { idx = Math.floor(Math.random() * PHRASES.length); }
  while (PHRASES.length > 1 && idx === lastIdx);
  lastIdx = idx;
  return PHRASES[idx];
}
