export const ITALIAN_PHRASES = [
  { it: "Buongiorno!", en: "Good morning!" },
  { it: "Buonasera!", en: "Good evening!" },
  { it: "Buonanotte!", en: "Good night!" },
  { it: "Ciao!", en: "Hi/Bye!" },
  { it: "A dopo!", en: "See you later!" },
  { it: "A domani!", en: "See you tomorrow!" },
  { it: "A presto!", en: "See you soon!" },
  { it: "Come va?", en: "How's it going?" },
  { it: "Come stai?", en: "How are you?" },
  { it: "Tutto bene.", en: "All good." },
  { it: "Non c'è male.", en: "Not bad." },
  { it: "Grazie!", en: "Thanks!" },
  { it: "Grazie mille.", en: "Thanks a lot." },
  { it: "Prego.", en: "You're welcome." },
  { it: "Per favore.", en: "Please." },
  { it: "Scusa.", en: "Sorry." },
  { it: "Mi dispiace.", en: "I'm sorry." },
  { it: "Nessun problema.", en: "No problem." },
  { it: "Tranquillo.", en: "Don't worry." },
  { it: "Un momento.", en: "One moment." },
  { it: "Arrivo subito.", en: "Be right there." },
  { it: "Sto arrivando.", en: "I'm on my way." },
  { it: "Sono in ritardo.", en: "I'm late." },
  { it: "Dove sei?", en: "Where are you?" },
  { it: "Dove ci vediamo?", en: "Where do we meet?" },
  { it: "A che ora?", en: "What time?" },
  { it: "Che ore sono?", en: "What time is it?" },
  { it: "Andiamo!", en: "Let's go!" },
  { it: "Aspetta!", en: "Wait!" },
  { it: "Capito.", en: "Got it." },
  { it: "Non capisco.", en: "I don't understand." },
  { it: "Puoi ripetere?", en: "Can you repeat?" },
  { it: "Parli inglese?", en: "Do you speak English?" },
  { it: "Dove si trova il bagno?", en: "Where is the bathroom?" },
  { it: "Quanto costa?", en: "How much is it?" },
  { it: "Va bene.", en: "Okay." },
  { it: "Certo.", en: "Sure." },
  { it: "Perfetto.", en: "Perfect." },
  { it: "Forse.", en: "Maybe." },
  { it: "Non lo so.", en: "I don't know." },
  { it: "Un caffè, per favore.", en: "A coffee, please." },
  { it: "Ho fame.", en: "I'm hungry." },
  { it: "Ho sete.", en: "I'm thirsty." },
  { it: "Buona giornata!", en: "Have a nice day!" },
  { it: "Buon weekend!", en: "Have a nice weekend!" },
  { it: "Buon lavoro!", en: "Have a good workday!" },
  { it: "In bocca al lupo!", en: "Good luck!" },
  { it: "Complimenti!", en: "Congrats!" },
  { it: "Ben fatto!", en: "Well done!" },
  { it: "Funziona.", en: "It works." },
  { it: "Non funziona.", en: "It doesn't work." },
  { it: "Va tutto bene.", en: "Everything's okay." },
  { it: "Che bello!", en: "How nice!" },
  { it: "Che peccato.", en: "What a pity." },
  { it: "Ti va?", en: "Feel like it?" },
  { it: "Volentieri.", en: "I'd love to." },
  { it: "Magari.", en: "Maybe." },
  { it: "Ti scrivo.", en: "I'll text you." },
  { it: "Ti chiamo.", en: "I'll call you." },
  { it: "Ci sentiamo.", en: "Talk soon." },
  { it: "Fatti sentire.", en: "Keep in touch." },
  { it: "Buon appetito!", en: "Enjoy your meal!" },
  { it: "Salute!", en: "Cheers!" },
  { it: "Attento!", en: "Watch out!" },
  { it: "Dai!", en: "Come on!" },
  { it: "Figurati.", en: "Don't mention it." },
  { it: "Come ti chiami?", en: "What's your name?" },
  { it: "Piacere di conoscerti.", en: "Nice to meet you." },
  { it: "Di dove sei?", en: "Where are you from?" },
  { it: "Sono di Roma.", en: "I'm from Rome." },
  { it: "Quanti anni hai?", en: "How old are you?" },
  { it: "Ho trent'anni.", en: "I'm thirty years old." },
  { it: "Dove abiti?", en: "Where do you live?" },
  { it: "Abito qui vicino.", en: "I live nearby." },
  { it: "Posso aiutarti?", en: "Can I help you?" },
  { it: "Mi puoi aiutare?", en: "Can you help me?" },
  { it: "Un attimo, per favore.", en: "One moment, please." },
  { it: "Niente di speciale.", en: "Nothing special." },
  { it: "Non è urgente.", en: "It's not urgent." },
  { it: "È urgente?", en: "Is it urgent?" },
  { it: "Che succede?", en: "What's happening?" },
  { it: "Tutto a posto?", en: "Everything okay?" },
  { it: "Sto bene, grazie.", en: "I'm fine, thanks." },
  { it: "E tu?", en: "And you?" },
  { it: "Ci vediamo lì.", en: "See you there." },
  { it: "A più tardi.", en: "See you later." },
  { it: "A tra poco.", en: "See you shortly." },
  { it: "Dammi un secondo.", en: "Give me a second." },
  { it: "Fammi sapere.", en: "Let me know." },
  { it: "Tienimi aggiornato.", en: "Keep me posted." },
  { it: "Nessuna fretta.", en: "No rush." },
  { it: "Prenditi il tuo tempo.", en: "Take your time." },
  { it: "Sto scherzando.", en: "I'm kidding." },
  { it: "È uno scherzo?", en: "Is it a joke?" },
  { it: "Sto solo guardando.", en: "I'm just looking." },
  { it: "Cerco questo.", en: "I'm looking for this." },
  { it: "Posso provare?", en: "Can I try?" },
  { it: "Posso sedermi qui?", en: "May I sit here?" },
  { it: "È occupato?", en: "Is this seat taken?" },
  { it: "Mi scusi.", en: "Excuse me." },
  { it: "Permesso.", en: "May I pass?" },
  { it: "Quanto tempo?", en: "How long?" },
  { it: "Quanto manca?", en: "How much longer?" },
  { it: "Quanto dista?", en: "How far is it?" },
  { it: "Che indirizzo?", en: "What's the address?" },
  { it: "Giri a destra.", en: "Turn right." },
  { it: "Giri a sinistra.", en: "Turn left." },
  { it: "Sempre dritto.", en: "Straight ahead." },
  { it: "All'angolo.", en: "At the corner." },
  { it: "Di fronte.", en: "Across the street." },
  { it: "Vicino alla stazione.", en: "Near the station." },
  { it: "Lontano da qui?", en: "Far from here?" },
  { it: "Che fermata è?", en: "Which stop is this?" },
  { it: "Quanto costa il biglietto?", en: "How much is the ticket?" },
  { it: "Un biglietto, per favore.", en: "One ticket, please." },
  { it: "A che ora parte?", en: "What time does it leave?" },
  { it: "A che ora arriva?", en: "What time does it arrive?" },
  { it: "Ho una prenotazione.", en: "I have a reservation." },
  { it: "A nome di...", en: "Under the name..." },
  { it: "Vorrei prenotare un tavolo.", en: "I'd like to book a table." },
  { it: "Quanti siete?", en: "How many people?" },
  { it: "Siamo in due.", en: "We are two." },
  { it: "Siamo in tre.", en: "We are three." },
  { it: "Un tavolo fuori, grazie.", en: "A table outside, please." },
  { it: "Il menù, per favore.", en: "The menu, please." },
  { it: "Consigli qualcosa?", en: "Do you recommend anything?" },
  { it: "Qual è la specialità?", en: "What's the specialty?" },
  { it: "Sono vegetariano.", en: "I'm vegetarian." },
  { it: "Sono vegano.", en: "I'm vegan." },
  { it: "Sono intollerante al lattosio.", en: "I'm lactose intolerant." },
  { it: "Niente glutine, grazie.", en: "No gluten, please." },
  { it: "Senza aglio, per favore.", en: "No garlic, please." },
  { it: "Acqua naturale, grazie.", en: "Still water, please." },
  { it: "Acqua frizzante, grazie.", en: "Sparkling water, please." },
  { it: "Il conto, per favore.", en: "The bill, please." },
  { it: "Possiamo dividere il conto?", en: "Can we split the bill?" },
  { it: "Paghiamo separati.", en: "Separate checks." },
  { it: "Pago io.", en: "I'll pay." },
  { it: "Accettate carte?", en: "Do you take cards?" },
  { it: "Posso pagare contactless?", en: "Can I pay contactless?" },
  { it: "Serve la ricevuta?", en: "Do you need a receipt?" },
  { it: "Mi fai lo scontrino?", en: "Can I get a receipt?" },
  { it: "Posso avere una busta?", en: "Can I get a bag?" },
  { it: "È in offerta?", en: "Is it on sale?" },
  { it: "Quanto pesa?", en: "How much does it weigh?" },
  { it: "È troppo caro.", en: "It's too expensive." },
  { it: "È economico.", en: "It's cheap." },
  { it: "Mi piace.", en: "I like it." },
  { it: "Non mi piace.", en: "I don't like it." }
];

export const SPANISH_PHRASES = [
  { es: "¡Hola!", en: "Hello!" },
  { es: "Buenos días.", en: "Good morning." },
  { es: "Buenas tardes.", en: "Good afternoon." },
  { es: "Buenas noches.", en: "Good night." },
  { es: "¿Qué tal?", en: "How's it going?" },
  { es: "¿Cómo estás?", en: "How are you?" },
  { es: "Muy bien, gracias.", en: "Very well, thanks." },
  { es: "¿Y tú?", en: "And you?" },
  { es: "Mucho gusto.", en: "Nice to meet you." },
  { es: "Un placer.", en: "A pleasure." },
  { es: "¿Cómo te llamas?", en: "What's your name?" },
  { es: "Me llamo...", en: "My name is..." },
  { es: "¿De dónde eres?", en: "Where are you from?" },
  { es: "Soy de Madrid.", en: "I'm from Madrid." },
  { es: "¿Dónde vives?", en: "Where do you live?" },
  { es: "Vivo cerca.", en: "I live nearby." },
  { es: "Por favor.", en: "Please." },
  { es: "Gracias.", en: "Thanks." },
  { es: "Muchas gracias.", en: "Thank you very much." },
  { es: "De nada.", en: "You're welcome." },
  { es: "Perdón.", en: "Sorry." },
  { es: "Lo siento.", en: "I'm sorry." },
  { es: "No hay problema.", en: "No problem." },
  { es: "Tranquilo.", en: "Don't worry." },
  { es: "Un momento.", en: "One moment." },
  { es: "Ahora voy.", en: "Be right there." },
  { es: "Estoy llegando.", en: "I'm on my way." },
  { es: "Llego tarde.", en: "I'm late." },
  { es: "¿Dónde estás?", en: "Where are you?" },
  { es: "¿Dónde nos vemos?", en: "Where do we meet?" },
  { es: "¿A qué hora?", en: "What time?" },
  { es: "¿Qué hora es?", en: "What time is it?" },
  { es: "¡Vamos!", en: "Let's go!" },
  { es: "Espera.", en: "Wait." },
  { es: "Entendido.", en: "Got it." },
  { es: "No entiendo.", en: "I don't understand." },
  { es: "¿Puedes repetir?", en: "Can you repeat?" },
  { es: "¿Hablas inglés?", en: "Do you speak English?" },
  { es: "¿Dónde está el baño?", en: "Where is the bathroom?" },
  { es: "¿Cuánto cuesta?", en: "How much is it?" },
  { es: "Está bien.", en: "Okay." },
  { es: "Claro.", en: "Sure." },
  { es: "Perfecto.", en: "Perfect." },
  { es: "Tal vez.", en: "Maybe." },
  { es: "No lo sé.", en: "I don't know." },
  { es: "Un café, por favor.", en: "A coffee, please." },
  { es: "Tengo hambre.", en: "I'm hungry." },
  { es: "Tengo sed.", en: "I'm thirsty." },
  { es: "¡Que tengas buen día!", en: "Have a nice day!" },
  { es: "Buen fin de semana.", en: "Have a nice weekend." },
  { es: "Buen trabajo.", en: "Good job." },
  { es: "¡Suerte!", en: "Good luck!" },
  { es: "¡Felicidades!", en: "Congrats!" },
  { es: "Bien hecho.", en: "Well done." },
  { es: "Funciona.", en: "It works." },
  { es: "No funciona.", en: "It doesn't work." },
  { es: "Todo bien.", en: "Everything's okay." },
  { es: "¡Qué bien!", en: "How nice!" },
  { es: "¡Qué pena!", en: "What a pity!" },
  { es: "¿Te apetece?", en: "Feel like it?" },
  { es: "Con gusto.", en: "I'd love to." },
  { es: "Ojalá.", en: "Hopefully." },
  { es: "Te escribo.", en: "I'll text you." },
  { es: "Te llamo.", en: "I'll call you." },
  { es: "Hablamos luego.", en: "Talk later." },
  { es: "Seguimos en contacto.", en: "Keep in touch." },
  { es: "¡Buen provecho!", en: "Enjoy your meal!" },
  { es: "¡Salud!", en: "Cheers!" },
  { es: "¡Cuidado!", en: "Watch out!" },
  { es: "¡Venga!", en: "Come on!" },
  { es: "¡Faltaría más!", en: "Don't mention it." },
  { es: "¿Cómo te va?", en: "How's it going?" },
  { es: "Nada especial.", en: "Nothing special." },
  { es: "No es urgente.", en: "It's not urgent." },
  { es: "¿Qué pasa?", en: "What's happening?" },
  { es: "¿Todo bien?", en: "Everything okay?" },
  { es: "Estoy bien, gracias.", en: "I'm fine, thanks." },
  { es: "Nos vemos ahí.", en: "See you there." },
  { es: "Nos vemos luego.", en: "See you later." },
  { es: "Hasta pronto.", en: "See you soon." },
  { es: "Hasta luego.", en: "See you later." },
  { es: "Hasta mañana.", en: "See you tomorrow." },
  { es: "Hasta ahora.", en: "See you soon." },
  { es: "Dame un segundo.", en: "Give me a second." },
  { es: "Avísame.", en: "Let me know." },
  { es: "Manténme al tanto.", en: "Keep me posted." },
  { es: "Sin prisa.", en: "No rush." },
  { es: "Tómate tu tiempo.", en: "Take your time." },
  { es: "Estoy bromeando.", en: "I'm kidding." },
  { es: "¿Es broma?", en: "Is it a joke?" },
  { es: "Solo estoy mirando.", en: "I'm just looking." },
  { es: "Busco esto.", en: "I'm looking for this." },
  { es: "¿Puedo probar?", en: "Can I try?" },
  { es: "¿Puedo sentarme aquí?", en: "May I sit here?" },
  { es: "¿Está ocupado?", en: "Is this seat taken?" },
  { es: "Disculpe.", en: "Excuse me." },
  { es: "Con permiso.", en: "May I pass?" },
  { es: "¿Cuánto tiempo?", en: "How long?" },
  { es: "¿Cuánto falta?", en: "How much longer?" },
  { es: "¿Qué distancia hay?", en: "How far is it?" },
  { es: "¿Cuál es la dirección?", en: "What's the address?" },
  { es: "Gire a la derecha.", en: "Turn right." },
  { es: "Gire a la izquierda.", en: "Turn left." },
  { es: "Todo recto.", en: "Straight ahead." },
  { es: "En la esquina.", en: "At the corner." },
  { es: "Enfrente.", en: "Across the street." },
  { es: "Cerca de la estación.", en: "Near the station." },
  { es: "¿Lejos de aquí?", en: "Far from here?" },
  { es: "¿Qué parada es?", en: "Which stop is this?" },
  { es: "¿Cuánto vale el billete?", en: "How much is the ticket?" },
  { es: "Un billete, por favor.", en: "One ticket, please." },
  { es: "¿A qué hora sale?", en: "What time does it leave?" },
  { es: "¿A qué hora llega?", en: "What time does it arrive?" },
  { es: "Tengo una reserva.", en: "I have a reservation." },
  { es: "A nombre de...", en: "Under the name..." },
  { es: "Quisiera reservar mesa.", en: "I'd like to book a table." },
  { es: "¿Cuántos son?", en: "How many people?" },
  { es: "Somos dos.", en: "We are two." },
  { es: "Somos tres.", en: "We are three." },
  { es: "Mesa afuera, por favor.", en: "A table outside, please." },
  { es: "El menú, por favor.", en: "The menu, please." },
  { es: "¿Recomienda algo?", en: "Do you recommend anything?" },
  { es: "¿Cuál es la especialidad?", en: "What's the specialty?" },
  { es: "Soy vegetariano.", en: "I'm vegetarian." },
  { es: "Soy vegano.", en: "I'm vegan." },
  { es: "Soy intolerante a la lactosa.", en: "I'm lactose intolerant." },
  { es: "Sin gluten, por favor.", en: "No gluten, please." },
  { es: "Sin ajo, por favor.", en: "No garlic, please." },
  { es: "Agua sin gas, gracias.", en: "Still water, please." },
  { es: "Agua con gas, gracias.", en: "Sparkling water, please." },
  { es: "La cuenta, por favor.", en: "The bill, please." },
  { es: "¿Dividimos la cuenta?", en: "Can we split the bill?" },
  { es: "Pagamos por separado.", en: "Separate checks." },
  { es: "Pago yo.", en: "I'll pay." },
  { es: "¿Aceptan tarjetas?", en: "Do you take cards?" },
  { es: "¿Puedo pagar contactless?", en: "Can I pay contactless?" },
  { es: "¿Quiere un recibo?", en: "Do you need a receipt?" },
  { es: "¿Me da un recibo?", en: "Can I get a receipt?" },
  { es: "¿Me da una bolsa?", en: "Can I get a bag?" },
  { es: "¿Está en oferta?", en: "Is it on sale?" },
  { es: "¿Cuánto pesa?", en: "How much does it weigh?" },
  { es: "Es muy caro.", en: "It's too expensive." },
  { es: "Es barato.", en: "It's cheap." },
  { es: "Me gusta.", en: "I like it." },
  { es: "No me gusta.", en: "I don't like it." },
  { es: "¿Puedes ayudarme?", en: "Can you help me?" },
  { es: "¿Dónde quedamos?", en: "Where shall we meet?" },
  { es: "¿Está abierto?", en: "Is it open?" },
  { es: "¿Está cerrado?", en: "Is it closed?" },
  { es: "¿Tienes cambio?", en: "Do you have change?" }
];

export const FRENCH_PHRASES = [
  { fr: "Bonjour !", en: "Good morning!" },
  { fr: "Bonsoir !", en: "Good evening!" },
  { fr: "Bonne nuit !", en: "Good night!" },
  { fr: "Salut !", en: "Hi/Bye!" },
  { fr: "À plus tard !", en: "See you later!" },
  { fr: "À demain !", en: "See you tomorrow!" },
  { fr: "À bientôt !", en: "See you soon!" },
  { fr: "Ça va ?", en: "How's it going?" },
  { fr: "Comment ça va ?", en: "How are you?" },
  { fr: "Comment tu vas ?", en: "How are you?" },
  { fr: "Comment allez-vous ?", en: "How are you?" },
  { fr: "Comment tu t'appelles ?", en: "What's your name?" },
  { fr: "Je m'appelle …", en: "My name is..." },
  { fr: "Ravi de te rencontrer.", en: "Nice to meet you." },
  { fr: "D'où viens-tu ?", en: "Where are you from?" },
  { fr: "Je viens de Paris.", en: "I'm from Paris." },
  { fr: "Tu habites où ?", en: "Where do you live?" },
  { fr: "J'habite tout près.", en: "I live nearby." },
  { fr: "S'il te plaît.", en: "Please." },
  { fr: "S'il vous plaît.", en: "Please." },
  { fr: "Merci !", en: "Thanks!" },
  { fr: "Merci beaucoup.", en: "Thanks a lot." },
  { fr: "De rien.", en: "You're welcome." },
  { fr: "Pardon.", en: "Sorry." },
  { fr: "Excuse-moi.", en: "Excuse me." },
  { fr: "Je suis désolé.", en: "I'm sorry." },
  { fr: "Désolé pour ça.", en: "Sorry about that." },
  { fr: "Pas de problème.", en: "No problem." },
  { fr: "T'inquiète pas.", en: "Don't worry." },
  { fr: "Un moment, s'il te plaît.", en: "One moment, please." },
  { fr: "J'arrive tout de suite.", en: "Be right there." },
  { fr: "J'arrive.", en: "I'm coming." },
  { fr: "Je suis en route.", en: "I'm on the way." },
  { fr: "Je suis en retard.", en: "I'm late." },
  { fr: "Tu es où ?", en: "Where are you?" },
  { fr: "On se voit où ?", en: "Where do we meet?" },
  { fr: "À quelle heure ?", en: "What time?" },
  { fr: "Il est quelle heure ?", en: "What time is it?" },
  { fr: "On y va !", en: "Let's go!" },
  { fr: "Attends !", en: "Wait!" },
  { fr: "C'est noté.", en: "Noted." },
  { fr: "Je ne comprends pas.", en: "I don't understand." },
  { fr: "Tu peux répéter ?", en: "Can you repeat?" },
  { fr: "Parles-tu anglais ?", en: "Do you speak English?" },
  { fr: "Où sont les toilettes ?", en: "Where is the bathroom?" },
  { fr: "Combien ça coûte ?", en: "How much is it?" },
  { fr: "C'est trop cher.", en: "It's too expensive." },
  { fr: "C'est bon marché.", en: "It's cheap." },
  { fr: "Ça marche.", en: "It works." },
  { fr: "Ça ne marche pas.", en: "It doesn't work." },
  { fr: "Tout va bien.", en: "Everything's okay." },
  { fr: "Super !", en: "Great!" },
  { fr: "Dommage.", en: "What a pity." },
  { fr: "Génial !", en: "Awesome!" },
  { fr: "Ça me va.", en: "Works for me." },
  { fr: "Je ne sais pas.", en: "I don't know." },
  { fr: "Peut-être.", en: "Maybe." },
  { fr: "Un café, s'il te plaît.", en: "A coffee, please." },
  { fr: "J'ai faim.", en: "I'm hungry." },
  { fr: "J'ai soif.", en: "I'm thirsty." },
  { fr: "Bonne journée !", en: "Have a nice day!" },
  { fr: "Bon week-end !", en: "Have a nice weekend!" },
  { fr: "Bon courage !", en: "Hang in there!" },
  { fr: "Bonne chance !", en: "Good luck!" },
  { fr: "Félicitations !", en: "Congrats!" },
  { fr: "Bien joué !", en: "Well played!" },
  { fr: "Bien fait !", en: "Well done!" },
  { fr: "Fais attention !", en: "Watch out!" },
  { fr: "Doucement !", en: "Take it easy!" },
  { fr: "Vas-y !", en: "Go for it!" },
  { fr: "Reviens !", en: "Come back!" },
  { fr: "Appelle-moi.", en: "Call me." },
  { fr: "Écris-moi.", en: "Text me." },
  { fr: "On se parle bientôt.", en: "Talk to you soon." },
  { fr: "Donne-moi des nouvelles.", en: "Keep me posted." },
  { fr: "Bon appétit !", en: "Enjoy your meal!" },
  { fr: "Santé !", en: "Cheers!" },
  { fr: "Où es-tu ?", en: "Where are you?" },
  { fr: "On se retrouve là.", en: "Meet you there." },
  { fr: "À plus.", en: "See ya." },
  { fr: "À tout à l'heure.", en: "See you later." },
  { fr: "À tout de suite.", en: "Be right back." },
  { fr: "Donne-moi une seconde.", en: "Give me a second." },
  { fr: "Tiens-moi au courant.", en: "Keep me posted." },
  { fr: "Pas de souci.", en: "No worries." },
  { fr: "Prends ton temps.", en: "Take your time." },
  { fr: "Je rigole.", en: "I'm kidding." },
  { fr: "C'est une blague ?", en: "Is it a joke?" },
  { fr: "Je regarde seulement.", en: "I'm just looking." },
  { fr: "Je cherche ça.", en: "I'm looking for this." },
  { fr: "Je peux essayer ?", en: "Can I try?" },
  { fr: "Je peux m'asseoir ici ?", en: "May I sit here?" },
  { fr: "C'est pris ?", en: "Is this seat taken?" },
  { fr: "Excusez-moi.", en: "Excuse me." },
  { fr: "Je peux passer ?", en: "May I pass?" },
  { fr: "Combien de temps ?", en: "How long?" },
  { fr: "Il reste combien ?", en: "How much longer?" },
  { fr: "C'est loin d'ici ?", en: "Is it far from here?" },
  { fr: "Quelle adresse ?", en: "What's the address?" },
  { fr: "Tournez à droite.", en: "Turn right." },
  { fr: "Tournez à gauche.", en: "Turn left." },
  { fr: "Tout droit.", en: "Straight ahead." },
  { fr: "Au coin.", en: "At the corner." },
  { fr: "En face.", en: "Across the street." },
  { fr: "Près de la gare.", en: "Near the station." },
  { fr: "Quel arrêt est-ce ?", en: "Which stop is this?" },
  { fr: "Quel quai, s'il vous plaît ?", en: "Which platform, please?" },
  { fr: "Un billet, s'il vous plaît.", en: "One ticket, please." },
  { fr: "C'est quelle voie ?", en: "Which track is it?" },
  { fr: "À quelle heure ça part ?", en: "What time does it leave?" },
  { fr: "À quelle heure ça arrive ?", en: "What time does it arrive?" },
  { fr: "J'ai une réservation.", en: "I have a reservation." },
  { fr: "Au nom de…", en: "Under the name..." },
  { fr: "Je voudrais réserver.", en: "I'd like to book." },
  { fr: "On est combien ?", en: "How many of us?" },
  { fr: "Nous sommes deux.", en: "We are two." },
  { fr: "Nous sommes trois.", en: "We are three." },
  { fr: "Une table dehors, s'il vous plaît.", en: "A table outside, please." },
  { fr: "La carte, s'il vous plaît.", en: "The menu, please." },
  { fr: "Que recommandez-vous ?", en: "Do you recommend anything?" },
  { fr: "Quelle est la spécialité ?", en: "What's the specialty?" },
  { fr: "Je suis végétarien.", en: "I'm vegetarian." },
  { fr: "Je suis végétalien.", en: "I'm vegan." },
  { fr: "Sans lactose, s'il vous plaît.", en: "No lactose, please." },
  { fr: "Sans gluten, s'il vous plaît.", en: "No gluten, please." },
  { fr: "Sans ail, s'il vous plaît.", en: "No garlic, please." },
  { fr: "De l'eau plate, merci.", en: "Still water, please." },
  { fr: "De l'eau gazeuse, merci.", en: "Sparkling water, please." },
  { fr: "L'addition, s'il vous plaît.", en: "The bill, please." },
  { fr: "On peut partager ?", en: "Can we split?" },
  { fr: "Séparons l'addition.", en: "Separate checks." },
  { fr: "Je paie.", en: "I'll pay." },
  { fr: "Vous prenez la carte ?", en: "Do you take cards?" },
  { fr: "Je peux payer sans contact ?", en: "Can I pay contactless?" },
  { fr: "Un reçu, s'il vous plaît.", en: "A receipt, please." },
  { fr: "Je peux avoir un sac ?", en: "Can I get a bag?" },
  { fr: "C'est en promotion ?", en: "Is it on sale?" },
  { fr: "Combien ça pèse ?", en: "How much does it weigh?" },
  { fr: "Je l'aime bien.", en: "I like it." },
  { fr: "Je n'aime pas.", en: "I don't like it." },
  { fr: "Ça me plaît.", en: "I like it." },
  { fr: "Ça ne me plaît pas.", en: "I don't like it." },
  { fr: "Il fait beau.", en: "It's nice weather." },
  { fr: "Il pleut.", en: "It's raining." },
  { fr: "Il fait froid.", en: "It's cold." },
  { fr: "Il fait chaud.", en: "It's hot." },
  { fr: "Quelle température aujourd'hui ?", en: "What's the temperature today?" },
  { fr: "Bon rétablissement !", en: "Get well soon!" },
  { fr: "Porte-toi bien.", en: "Take care." }
];

export const JAPANESE_PHRASES = [
  { ja: "こんにちは。", en: "Hello." },
  { ja: "おはようございます。", en: "Good morning." },
  { ja: "こんばんは。", en: "Good evening." },
  { ja: "おやすみなさい。", en: "Good night." },
  { ja: "やあ。", en: "Hi." },
  { ja: "またね。", en: "See you." },
  { ja: "また明日。", en: "See you tomorrow." },
  { ja: "また後で。", en: "See you later." },
  { ja: "すぐ戻ります。", en: "Be right back." },
  { ja: "元気ですか？", en: "How are you?" },
  { ja: "元気です。", en: "I’m fine." },
  { ja: "まあまあです。", en: "So-so." },
  { ja: "ありがとうございます。", en: "Thank you very much." },
  { ja: "ありがとう。", en: "Thanks." },
  { ja: "どういたしまして。", en: "You’re welcome." },
  { ja: "すみません。", en: "Excuse me." },
  { ja: "ごめんなさい。", en: "I’m sorry." },
  { ja: "大丈夫です。", en: "It’s okay." },
  { ja: "問題ありません。", en: "No problem." },
  { ja: "心配しないで。", en: "Don’t worry." },
  { ja: "少々お待ちください。", en: "One moment, please." },
  { ja: "ちょっと待って。", en: "Wait a sec." },
  { ja: "今向かっています。", en: "I’m on my way." },
  { ja: "遅れます。", en: "I’ll be late." },
  { ja: "どこにいますか？", en: "Where are you?" },
  { ja: "ここにいます。", en: "I’m here." },
  { ja: "どこで会いますか？", en: "Where do we meet?" },
  { ja: "何時に？", en: "At what time?" },
  { ja: "今何時ですか？", en: "What time is it?" },
  { ja: "行きましょう！", en: "Let’s go!" },
  { ja: "わかりました。", en: "Got it." },
  { ja: "わかりません。", en: "I don’t understand." },
  { ja: "もう一度お願いします。", en: "Please repeat." },
  { ja: "英語は話せますか？", en: "Do you speak English?" },
  { ja: "日本語は少しだけ。", en: "I speak a little Japanese." },
  { ja: "手伝ってくれますか？", en: "Can you help me?" },
  { ja: "助けてください。", en: "Help me, please." },
  { ja: "どこですか？", en: "Where is it?" },
  { ja: "トイレはどこですか？", en: "Where is the restroom?" },
  { ja: "駅はどこですか？", en: "Where is the station?" },
  { ja: "コンビニはどこ？", en: "Where’s a convenience store?" },
  { ja: "いくらですか？", en: "How much is it?" },
  { ja: "これはいくら？", en: "How much is this?" },
  { ja: "安くなりますか？", en: "Can you discount?" },
  { ja: "高いですね。", en: "It’s expensive." },
  { ja: "安いですね。", en: "It’s cheap." },
  { ja: "これが好きです。", en: "I like this." },
  { ja: "これは好きじゃない。", en: "I don’t like this." },
  { ja: "お願いします。", en: "Please." },
  { ja: "いいですよ。", en: "Sure." },
  { ja: "だめです。", en: "No good." },
  { ja: "たぶん。", en: "Maybe." },
  { ja: "知りません。", en: "I don’t know." },
  { ja: "了解です。", en: "Roger that." },
  { ja: "お手洗いを借ります。", en: "May I use the restroom?" },
  { ja: "写真を撮ってもいい？", en: "May I take a photo?" },
  { ja: "ここに座ってもいい？", en: "May I sit here?" },
  { ja: "予約しています。", en: "I have a reservation." },
  { ja: "名前は…です。", en: "The name is..." },
  { ja: "二人です。", en: "Two people." },
  { ja: "三人です。", en: "Three people." },
  { ja: "メニューをください。", en: "The menu, please." },
  { ja: "おすすめは何ですか？", en: "What do you recommend?" },
  { ja: "ベジタリアンです。", en: "I’m vegetarian." },
  { ja: "ヴィーガンです。", en: "I’m vegan." },
  { ja: "辛くしないでください。", en: "Not spicy, please." },
  { ja: "にんにく抜きで。", en: "No garlic, please." },
  { ja: "水をください。", en: "Water, please." },
  { ja: "炭酸水をください。", en: "Sparkling water, please." },
  { ja: "会計お願いします。", en: "Check, please." },
  { ja: "別々でお願いします。", en: "Separate checks, please." },
  { ja: "カード使えますか？", en: "Do you take cards?" },
  { ja: "タッチ決済できますか？", en: "Contactless payment?" },
  { ja: "レシートをください。", en: "Receipt, please." },
  { ja: "袋をください。", en: "A bag, please." },
  { ja: "道に迷いました。", en: "I’m lost." },
  { ja: "右に曲がってください。", en: "Turn right." },
  { ja: "左に曲がってください。", en: "Turn left." },
  { ja: "まっすぐ進んでください。", en: "Go straight." },
  { ja: "ここで止めてください。", en: "Stop here, please." },
  { ja: "これはどの電車？", en: "Which train is this?" },
  { ja: "何番ホームですか？", en: "Which platform?" },
  { ja: "次の駅はどこ？", en: "What’s the next stop?" },
  { ja: "いつ出発しますか？", en: "When does it leave?" },
  { ja: "いつ到着しますか？", en: "When does it arrive?" },
  { ja: "この席は空いてますか？", en: "Is this seat free?" },
  { ja: "Wi-Fiはありますか？", en: "Is there Wi-Fi?" },
  { ja: "パスワードは何ですか？", en: "What’s the password?" },
  { ja: "充電してもいいですか？", en: "May I charge here?" },
  { ja: "電波が悪いです。", en: "The signal is bad." },
  { ja: "今日は暑いですね。", en: "It’s hot today." },
  { ja: "今日は寒いですね。", en: "It’s cold today." },
  { ja: "いい天気ですね。", en: "Nice weather." },
  { ja: "雨が降っています。", en: "It’s raining." },
  { ja: "雪が降っています。", en: "It’s snowing." },
  { ja: "体調が悪いです。", en: "I feel sick." },
  { ja: "気分がいいです。", en: "I feel good." },
  { ja: "お大事に。", en: "Get well soon." },
  { ja: "お疲れさま。", en: "Good job." },
  { ja: "がんばって！", en: "Good luck!" },
  { ja: "おめでとう！", en: "Congratulations!" },
  { ja: "すごい！", en: "Awesome!" },
  { ja: "最高！", en: "The best!" },
  { ja: "残念です。", en: "What a pity." },
  { ja: "いいね。", en: "Nice." },
  { ja: "なるほど。", en: "I see." },
  { ja: "ちょうどいい。", en: "Just right." },
  { ja: "少し待って。", en: "Wait a moment." },
  { ja: "今大丈夫ですか？", en: "Is now okay?" },
  { ja: "後で話しましょう。", en: "Let’s talk later." },
  { ja: "連絡します。", en: "I’ll contact you." },
  { ja: "連絡ください。", en: "Please contact me." },
  { ja: "メッセージ送ります。", en: "I’ll send a message." },
  { ja: "電話します。", en: "I’ll call you." },
  { ja: "返事ください。", en: "Please reply." },
  { ja: "間違えました。", en: "My mistake." },
  { ja: "大丈夫でしょうか？", en: "Is that okay?" },
  { ja: "できますか？", en: "Can you do it?" },
  { ja: "できません。", en: "I can’t." },
  { ja: "できます。", en: "I can." },
  { ja: "試してみます。", en: "I’ll try." },
  { ja: "助かります。", en: "That helps." },
  { ja: "助かりました。", en: "That helped." },
  { ja: "忘れました。", en: "I forgot." },
  { ja: "覚えています。", en: "I remember." },
  { ja: "もう一度見せて。", en: "Show me again." },
  { ja: "どれがおすすめ？", en: "Which do you recommend?" },
  { ja: "写真を見せてください。", en: "Show a photo, please." },
  { ja: "開いていますか？", en: "Are you open?" },
  { ja: "閉まっていますか？", en: "Are you closed?" },
  { ja: "営業時間は？", en: "Business hours?" },
  { ja: "トラブルです。", en: "There’s a problem." },
  { ja: "修理が必要です。", en: "Needs repair." },
  { ja: "予約できますか？", en: "Can I book?" },
  { ja: "キャンセルできますか？", en: "Can I cancel?" },
  { ja: "返金できますか？", en: "Can I get a refund?" },
  { ja: "配達できますか？", en: "Do you deliver?" },
  { ja: "持ち帰りでお願いします。", en: "To go, please." },
  { ja: "店内でお願いします。", en: "For here, please." },
  { ja: "もう少しください。", en: "A little more, please." },
  { ja: "少なめでお願いします。", en: "Less, please." },
  { ja: "砂糖抜きで。", en: "No sugar, please." },
  { ja: "ミルクなしで。", en: "No milk, please." },
  { ja: "氷なしで。", en: "No ice, please." },
  { ja: "辛さは普通で。", en: "Medium spice." },
  { ja: "写真撮ってください。", en: "Please take a photo." },
  { ja: "先にどうぞ。", en: "After you." },
  { ja: "お先に失礼します。", en: "I’ll head out first." },
  { ja: "お久しぶりです。", en: "Long time no see." },
  { ja: "よろしくお願いします。", en: "Nice to meet you." }
];




let lastItalianIdx = -1;
let lastSpanishIdx = -1;
let lastFrenchIdx = -1;
let lastJapaneseIdx = -1;

export function randomPhraseNoRepeat(language = 'italian') {
  if (language === 'spanish') {
    if (SPANISH_PHRASES.length === 0) return { es: "¡Hola!", en: "Hello!" };
    let idx;
    do { idx = Math.floor(Math.random() * SPANISH_PHRASES.length); }
    while (SPANISH_PHRASES.length > 1 && idx === lastSpanishIdx);
    lastSpanishIdx = idx;
    return SPANISH_PHRASES[idx];
  } else if (language === 'french') {
    if (FRENCH_PHRASES.length === 0) return { fr: "Bonjour!", en: "Hello!" };
    let idx;
    do { idx = Math.floor(Math.random() * FRENCH_PHRASES.length); }
    while (FRENCH_PHRASES.length > 1 && idx === lastFrenchIdx);
    lastFrenchIdx = idx;
    return FRENCH_PHRASES[idx];
  } else if (language === 'japanese') {
    if (JAPANESE_PHRASES.length === 0) return { ja: "こんにちは！", en: "Hello!" };
    let idx;
    do { idx = Math.floor(Math.random() * JAPANESE_PHRASES.length); }
    while (JAPANESE_PHRASES.length > 1 && idx === lastJapaneseIdx);
    lastJapaneseIdx = idx;
    return JAPANESE_PHRASES[idx];
  } else {
    if (ITALIAN_PHRASES.length === 0) return { it: "Ciao!", en: "Hi!" };
    let idx;
    do { idx = Math.floor(Math.random() * ITALIAN_PHRASES.length); }
    while (ITALIAN_PHRASES.length > 1 && idx === lastItalianIdx);
    lastItalianIdx = idx;
    return ITALIAN_PHRASES[idx];
  }
}
