export const ITALIAN_PHRASES_EASY = [
  { it: "Buongiorno!", en: "Good morning!" },
  { it: "Buonasera!", en: "Good evening!" },
  { it: "Buonanotte!", en: "Good night!" },
  { it: "Ciao!", en: "Hi/Bye!" },
  { it: "A dopo!", en: "See you later!" },
  { it: "A domani!", en: "See you tomorrow!" },
  { it: "Come va?", en: "How's it going?" },
  { it: "Come stai?", en: "How are you?" },
  { it: "Tutto bene.", en: "All good." },
  { it: "Grazie!", en: "Thanks!" },
  { it: "Prego.", en: "You're welcome." },
  { it: "Per favore.", en: "Please." },
  { it: "Scusa.", en: "Sorry." },
  { it: "Un momento.", en: "One moment." },
  { it: "Dove sei?", en: "Where are you?" },
  { it: "A che ora?", en: "What time?" },
  { it: "Che ore sono?", en: "What time is it?" },
  { it: "Andiamo!", en: "Let's go!" },
  { it: "Aspetta!", en: "Wait!" },
  { it: "Ho capito.", en: "I understood." },
  { it: "Non capisco.", en: "I don't understand." },
  { it: "Quanto costa?", en: "How much is it?" },
  { it: "Va bene.", en: "Okay." },
  { it: "Certo.", en: "Sure." },
  { it: "Non lo so.", en: "I don't know." },
  { it: "Un caffè, per favore.", en: "A coffee, please." },
  { it: "Ho fame.", en: "I'm hungry (I have hunger)" },
  { it: "Ho sete.", en: "I'm thirsty (I have thirst)" },
  { it: "Buona giornata!", en: "Have a nice day!" },
  { it: "Complimenti!", en: "Congrats!" },
  { it: "Che bello!", en: "How nice!" },
  { it: "Ti va?", en: "Are you up for it?" },
  { it: "Volentieri.", en: "I'd love to." },
  { it: "Ti scrivo.", en: "I'll text you." },
  { it: "Ti chiamo.", en: "I'll call you." },
  { it: "Buon appetito!", en: "Enjoy your meal!" },
  { it: "Salute!", en: "Cheers!" },
  { it: "Attento!", en: "Watch out!" },
  { it: "Dai!", en: "Come on!" },
  { it: "Come ti chiami?", en: "What's your name?" },
  { it: "Piacere di conoscerti.", en: "Nice to meet you." },
  { it: "Di dove sei?", en: "Where are you from?" },
  { it: "Sono di Roma.", en: "I'm from Rome." },
  { it: "Dove abiti?", en: "Where do you live?" },
  { it: "Posso aiutarti?", en: "Can I help you?" },
  { it: "Mi puoi aiutare?", en: "Can you help me?" },
  { it: "Che succede?", en: "What's happening?" },
  { it: "Tutto a posto?", en: "Everything okay?" },
  { it: "Sto bene, grazie.", en: "I'm fine, thanks." },
  { it: "E tu?", en: "And you?" },
  { it: "Ci vediamo lì.", en: "See you there." },
  // New additions
  { it: "Mi chiamo...", en: "My name is..." },
  { it: "Perfetto!", en: "Perfect!" },
  { it: "Fantastico!", en: "Fantastic!" },
  { it: "Davvero?", en: "Really?" },
  { it: "Certo che sì!", en: "Of course!" },
  { it: "Assolutamente!", en: "Absolutely!" },
  { it: "Magari!", en: "I wish!" },
  { it: "Forse.", en: "Maybe." },
  { it: "Probabile.", en: "Probably." },
  { it: "Esatto!", en: "Exactly!" },
  { it: "Giusto!", en: "Right!" },
  { it: "Vai!", en: "Go!" },
  { it: "Fermati!", en: "Stop!" },
  { it: "Basta!", en: "Enough!" },
  { it: "Ancora.", en: "Again." },
  { it: "Subito.", en: "Right away." },
  { it: "Adesso.", en: "Now." },
  { it: "Più tardi.", en: "Later." },
  { it: "Oggi.", en: "Today." },
  { it: "Domani.", en: "Tomorrow." },
  { it: "Ieri.", en: "Yesterday." },
  { it: "Sempre.", en: "Always." },
  { it: "Mai.", en: "Never." },
  { it: "A presto!", en: "See you soon!" },
  { it: "Buon viaggio!", en: "Have a good trip!" },
  { it: "Buona fortuna!", en: "Good luck!" },
  { it: "Buon lavoro!", en: "Have a good day at work!" },
  { it: "Buon weekend!", en: "Have a good weekend!" },
  { it: "Che bella sorpresa!", en: "What a nice surprise!" },
  { it: "Mi dispiace.", en: "I'm sorry." },
  { it: "Scusami.", en: "Forgive me." },
  { it: "Non c'è problema.", en: "No problem." },
  { it: "Tranquillo.", en: "Don't worry." },
  { it: "D'accordo.", en: "Agreed." },
  { it: "Figurati!", en: "Don't mention it!" },
  { it: "Con piacere.", en: "With pleasure." },
  { it: "Molto gentile.", en: "Very kind." },
  { it: "Sei molto gentile.", en: "You're very kind." },
  { it: "Sono stanco.", en: "I'm tired." },
  { it: "Ho sonno.", en: "I'm sleepy (I have sleepiness)" },
  { it: "Ho freddo.", en: "I'm cold (I have coldness)" },
  { it: "Ho caldo.", en: "I'm hot (I have heat)" },
  { it: "Che caldo!", en: "It's so hot!" },
  { it: "Che freddo!", en: "It's so cold!" },
  { it: "Fa bel tempo.", en: "The weather is nice." },
  { it: "Piove.", en: "It's raining." },
  { it: "Nevica.", en: "It's snowing." },
  { it: "C'è il sole.", en: "It's sunny." },
  { it: "Che bel sole!", en: "What beautiful sunshine!" },
  { it: "Torno subito.", en: "I'll be right back." },
  { it: "Ci sono.", en: "I'm here." },
  { it: "Arrivo!", en: "I'm coming!" }
];

export const ITALIAN_PHRASES_MEDIUM = [
  { it: "Qual è il tuo cognome?", en: "What's your last name?" },
  { it: "Quanti anni hai?", en: "How old are you?" },
  { it: "Dove ci incontriamo?", en: "Where shall we meet?" },
  { it: "A che ora ci vediamo?", en: "What time shall we meet?" },
  { it: "Sto arrivando, arrivo tra poco.", en: "I'm on my way, shortly." },
  { it: "Sono in ritardo di cinque minuti.", en: "I'm five minutes late." },
  { it: "Possiamo sentirci più tardi?", en: "Can we talk later?" },
  { it: "Che cosa fai stasera?", en: "What are you doing tonight?" },
  { it: "Hai voglia di uscire?", en: "Do you feel like going out? (Do you have desire to go out?)" },
  { it: "Ci vediamo all'ingresso principale.", en: "See you at the main entrance." },
  { it: "Dove si trova il bagno?", en: "Where is the bathroom?" },
  { it: "Mi dispiace, non posso.", en: "Sorry, I can't." },
  { it: "Non ho capito bene.", en: "I didn't quite understand." },
  { it: "Parli più lentamente, per favore.", en: "Speak more slowly, please." },
  { it: "Puoi ripetere, per favore?", en: "Can you repeat, please?" },
  { it: "Come si dice 'this' in italiano?", en: "How do you say 'this' in Italian?" },
  { it: "Dove posso comprare i biglietti?", en: "Where can I buy tickets?" },
  { it: "Vorrei prenotare un tavolo, grazie.", en: "I'd like to book a table, thanks." },
  { it: "Per quanti siete?", en: "How many of you?" },
  { it: "Cosa consigli da mangiare?", en: "What do you recommend to eat?" },
  { it: "Ci può portare il conto, per favore?", en: "Could you bring us the bill, please?" },
  { it: "Mi sono perso.", en: "I'm lost." },
  { it: "Quanto ci vuole per arrivare?", en: "How long does it take to get there?" },
  { it: "È lontano da qui?", en: "Is it far from here?" },
  { it: "Vado in ufficio in autobus.", en: "I go to the office by bus." },
  { it: "Com'è andata la giornata?", en: "How did your day go?" },
  { it: "Che tempo fa oggi?", en: "What's the weather like today?" },
  { it: "Ho voglia di una pizza.", en: "I feel like a pizza (I have desire for a pizza)" },
  { it: "Preferisci il tè o il caffè?", en: "Do you prefer tea or coffee?" },
  { it: "Posso pagare con carta?", en: "Can I pay by card?" },
  { it: "Hai già mangiato?", en: "Have you eaten already?" },
  { it: "Ci sentiamo domani mattina.", en: "Talk tomorrow morning." },
  { it: "Mandami la posizione, per favore.", en: "Send me your location, please." },
  { it: "Ti mando il link tra poco.", en: "I'll send the link shortly." },
  { it: "A che piano abiti?", en: "What floor do you live on?" },
  { it: "Sei libero questo weekend?", en: "Are you free this weekend?" },
  { it: "Possiamo vederci verso le otto?", en: "Can we meet around eight?" },
  { it: "Devo alzarmi presto domani.", en: "I have to get up early tomorrow." },
  { it: "Sto cercando lavoro.", en: "I'm looking for a job." },
  { it: "Non ho campo qui dentro.", en: "I have no signal in here." },
  { it: "Mi mandi un messaggio quando arrivi?", en: "Will you message me when you arrive?" },
  { it: "Mi fa male la testa.", en: "My head hurts." },
  { it: "Puoi tenere d'occhio la borsa?", en: "Can you keep an eye on the bag?" },
  { it: "Non preoccuparti, ci penso io.", en: "Don't worry, I'll take care of it." },
  { it: "Va bene per le sette?", en: "Is seven okay?" },
  { it: "Hai bisogno di una mano?", en: "Do you need a hand?" },
  { it: "Dopo il lavoro passo da te.", en: "I'll stop by your place after work." },
  { it: "Metti pure la musica.", en: "Go ahead and put on some music." },
  { it: "Ci vediamo davanti alla stazione.", en: "See you in front of the station." },
  { it: "Scendo alla prossima fermata.", en: "I'm getting off at the next stop." },
  { it: "Puoi consigliarmi un buon ristorante?", en: "Can you recommend a good restaurant?" },
  // New additions
  { it: "Quanto tempo ci metti per arrivare?", en: "How long does it take you to get there?" },
  { it: "Posso offrirti qualcosa da bere?", en: "Can I offer you something to drink?" },
  { it: "Che cosa ti piacerebbe fare?", en: "What would you like to do?" },
  { it: "Hai visto il mio telefono?", en: "Have you seen my phone?" },
  { it: "Non riesco a trovare le chiavi.", en: "I can't find my keys." },
  { it: "Devo andare via tra cinque minuti.", en: "I have to leave in five minutes." },
  { it: "Sto aspettando un amico.", en: "I'm waiting for a friend." },
  { it: "Quanto tempo ti fermi qui?", en: "How long are you staying here?" },
  { it: "È la prima volta che vengo qui.", en: "It's my first time here." },
  { it: "Puoi spiegarmelo di nuovo?", en: "Can you explain it to me again?" },
  { it: "Non mi sento molto bene.", en: "I don't feel very well." },
  { it: "Ho bisogno di riposare un po'.", en: "I need to rest a bit (I have need to rest a bit)" },
  { it: "Dove hai comprato questa cosa?", en: "Where did you buy this?" },
  { it: "Quanto costa il biglietto?", en: "How much is the ticket?" },
  { it: "C'è uno sconto per studenti?", en: "Is there a student discount?" },
  { it: "Accettate contanti?", en: "Do you accept cash?" },
  { it: "Dove posso cambiare i soldi?", en: "Where can I exchange money?" },
  { it: "C'è una farmacia qui vicino?", en: "Is there a pharmacy nearby?" },
  { it: "Devo prendere una medicina.", en: "I need to take medicine." },
  { it: "Hai l'orario degli autobus?", en: "Do you have the bus schedule?" },
  { it: "Quando parte il prossimo treno?", en: "When does the next train leave?" },
  { it: "Posso sedermi qui?", en: "Can I sit here?" },
  { it: "Questo posto è libero?", en: "Is this seat free?" },
  { it: "Scusa, posso passare?", en: "Excuse me, can I get through?" },
  { it: "Non l'ho mai fatto prima.", en: "I've never done this before." },
  { it: "Come funziona questa cosa?", en: "How does this thing work?" },
  { it: "Puoi mostrarmi come si fa?", en: "Can you show me how to do it?" },
  { it: "Non sono sicuro di aver capito.", en: "I'm not sure I understood." },
  { it: "Potresti parlare un po' più forte?", en: "Could you speak a bit louder?" },
  { it: "La musica è troppo alta.", en: "The music is too loud." },
  { it: "Fa troppo caldo qui dentro.", en: "It's too hot in here." },
  { it: "Possiamo aprire la finestra?", en: "Can we open the window?" },
  { it: "Hai fame? Ordiniamo qualcosa.", en: "Are you hungry? Let's order something." },
  { it: "Cosa ti va di bere?", en: "What would you like to drink?" },
  { it: "Prendi pure quello che vuoi.", en: "Take whatever you want." },
  { it: "Mi fai vedere il menu?", en: "Will you show me the menu?" },
  { it: "Sono allergico a...", en: "I'm allergic to..." },
  { it: "Questo piatto è piccante?", en: "Is this dish spicy?" },
  { it: "Qual è la specialità della casa?", en: "What's the house specialty?" },
  { it: "Vorrei ordinare questo.", en: "I'd like to order this." },
  { it: "Quanto tempo ci vuole?", en: "How long will it take?" },
  { it: "Posso avere un bicchiere d'acqua?", en: "Can I have a glass of water?" },
  { it: "È incluso nel prezzo?", en: "Is it included in the price?" },
  { it: "Devo prenotare in anticipo?", en: "Do I need to book in advance?" },
  { it: "A che ora chiudete?", en: "What time do you close?" },
  { it: "A che ora aprite domani?", en: "What time do you open tomorrow?" },
  { it: "Posso provarlo prima?", en: "Can I try it first?" },
  { it: "Ce l'avete in un'altra taglia?", en: "Do you have it in another size?" },
  { it: "Posso restituirlo se non va bene?", en: "Can I return it if it doesn't fit?" },
  { it: "Avete il wifi qui?", en: "Do you have wifi here?" },
  { it: "Qual è la password del wifi?", en: "What's the wifi password?" }
];

export const SPANISH_PHRASES_EASY = [
  { es: "¡Hola!", en: "Hello!" },
  { es: "Buenos días.", en: "Good morning." },
  { es: "Buenas tardes.", en: "Good afternoon." },
  { es: "Buenas noches.", en: "Good night." },
  { es: "¿Qué tal?", en: "How's it going?" },
  { es: "¿Cómo estás?", en: "How are you?" },
  { es: "Muy bien, gracias.", en: "Very well, thanks." },
  { es: "¿Y tú?", en: "And you?" },
  { es: "Mucho gusto.", en: "Nice to meet you." },
  { es: "¿Cómo te llamas?", en: "What's your name?" },
  { es: "Me llamo...", en: "My name is..." },
  { es: "¿De dónde eres?", en: "Where are you from?" },
  { es: "Soy de Madrid.", en: "I'm from Madrid." },
  { es: "¿Dónde vives?", en: "Where do you live?" },
  { es: "Por favor.", en: "Please." },
  { es: "Gracias.", en: "Thanks." },
  { es: "De nada.", en: "You're welcome." },
  { es: "Perdón.", en: "Sorry." },
  { es: "Un momento.", en: "One moment." },
  { es: "¿Dónde estás?", en: "Where are you?" },
  { es: "¿A qué hora?", en: "What time?" },
  { es: "¿Qué hora es?", en: "What time is it?" },
  { es: "¡Vamos!", en: "Let's go!" },
  { es: "Espera.", en: "Wait." },
  { es: "No entiendo.", en: "I don't understand." },
  { es: "¿Cuánto cuesta?", en: "How much is it?" },
  { es: "Está bien.", en: "Okay." },
  { es: "Claro.", en: "Sure." },
  { es: "No lo sé.", en: "I don't know." },
  { es: "Un café, por favor.", en: "A coffee, please." },
  { es: "Tengo hambre.", en: "I'm hungry (I have hunger)" },
  { es: "Tengo sed.", en: "I'm thirsty (I have thirst)" },
  { es: "¡Que tengas buen día!", en: "Have a nice day!" },
  { es: "¡Suerte!", en: "Good luck!" },
  { es: "¡Felicidades!", en: "Congrats!" },
  { es: "Funciona.", en: "It works." },
  { es: "No funciona.", en: "It doesn't work." },
  { es: "Todo bien.", en: "Everything's okay." },
  { es: "¡Qué bien!", en: "How nice!" },
  { es: "¿Te apetece?", en: "Feel like it?" },
  { es: "Te escribo.", en: "I'll text you." },
  { es: "Te llamo.", en: "I'll call you." },
  { es: "¡Buen provecho!", en: "Enjoy your meal!" },
  { es: "¡Salud!", en: "Cheers!" },
  { es: "¡Cuidado!", en: "Watch out!" },
  { es: "¡Venga!", en: "Come on!" },
  { es: "¿Cómo te va?", en: "How's it going?" },
  { es: "¿Qué pasa?", en: "What's happening?" },
  { es: "¿Todo bien?", en: "Everything okay?" },
  { es: "Estoy bien, gracias.", en: "I'm fine, thanks." },
  { es: "Nos vemos ahí.", en: "See you there." },
  // New additions
  { es: "¡Perfecto!", en: "Perfect!" },
  { es: "¡Genial!", en: "Great!" },
  { es: "¡Increíble!", en: "Incredible!" },
  { es: "¿De verdad?", en: "Really?" },
  { es: "¡Por supuesto!", en: "Of course!" },
  { es: "¡Exacto!", en: "Exactly!" },
  { es: "Tal vez.", en: "Maybe." },
  { es: "Seguro.", en: "Sure." },
  { es: "Vale.", en: "Okay." },
  { es: "¡Para!", en: "Stop!" },
  { es: "Otra vez.", en: "Again." },
  { es: "Ahora.", en: "Now." },
  { es: "Luego.", en: "Later." },
  { es: "Hoy.", en: "Today." },
  { es: "Mañana.", en: "Tomorrow." },
  { es: "Ayer.", en: "Yesterday." },
  { es: "Siempre.", en: "Always." },
  { es: "Nunca.", en: "Never." },
  { es: "¡Hasta luego!", en: "See you later!" },
  { es: "¡Hasta pronto!", en: "See you soon!" },
  { es: "¡Buen viaje!", en: "Have a good trip!" },
  { es: "¡Buen fin de semana!", en: "Have a good weekend!" },
  { es: "¡Qué sorpresa!", en: "What a surprise!" },
  { es: "Lo siento.", en: "I'm sorry." },
  { es: "Perdóname.", en: "Forgive me." },
  { es: "No hay problema.", en: "No problem." },
  { es: "No pasa nada.", en: "It's nothing." },
  { es: "Tranquilo.", en: "Relax." },
  { es: "De acuerdo.", en: "Agreed." },
  { es: "Con mucho gusto.", en: "With pleasure." },
  { es: "Muy amable.", en: "Very kind." },
  { es: "Eres muy amable.", en: "You're very kind." },
  { es: "Estoy cansado.", en: "I'm tired." },
  { es: "Tengo sueño.", en: "I'm sleepy (I have sleep)" },
  { es: "Tengo frío.", en: "I'm cold (I have cold)" },
  { es: "Tengo calor.", en: "I'm hot (I have heat)" },
  { es: "Hace calor.", en: "It's hot." },
  { es: "Hace frío.", en: "It's cold." },
  { es: "Hace buen tiempo.", en: "The weather is nice." },
  { es: "Está lloviendo.", en: "It's raining." },
  { es: "Está nevando.", en: "It's snowing." },
  { es: "Hace sol.", en: "It's sunny." },
  { es: "Vuelvo enseguida.", en: "I'll be right back." },
  { es: "Aquí estoy.", en: "I'm here." },
  { es: "¡Ya voy!", en: "I'm coming!" },
  { es: "¡Enhorabuena!", en: "Congratulations!" },
  { es: "¡Ánimo!", en: "Cheer up!" },
  { es: "¡Qué guay!", en: "How cool!" },
  { es: "Me gusta.", en: "I like it." },
  { es: "No me gusta.", en: "I don't like it." }
];

export const SPANISH_PHRASES_MEDIUM = [
  { es: "¿Cuál es tu apellido?", en: "What's your last name?" },
  { es: "¿Cuántos años tienes?", en: "How old are you?" },
  { es: "¿Dónde nos encontramos?", en: "Where shall we meet?" },
  { es: "¿A qué hora quedamos?", en: "What time shall we meet?" },
  { es: "Ya voy, llego en un momento.", en: "I'm coming, arriving in a moment." },
  { es: "Llego cinco minutos tarde.", en: "I'm five minutes late." },
  { es: "¿Podemos hablar más tarde?", en: "Can we talk later?" },
  { es: "¿Qué haces esta noche?", en: "What are you doing tonight?" },
  { es: "¿Quieres salir conmigo?", en: "Do you want to go out with me?" },
  { es: "Nos vemos en la entrada principal.", en: "See you at the main entrance." },
  { es: "¿Dónde está el baño?", en: "Where is the bathroom?" },
  { es: "Lo siento, no puedo.", en: "Sorry, I can't." },
  { es: "No entendí bien.", en: "I didn't quite understand." },
  { es: "Habla más despacio, por favor.", en: "Speak more slowly, please." },
  { es: "¿Puedes repetir, por favor?", en: "Can you repeat, please?" },
  { es: "¿Cómo se dice 'esto' en español?", en: "How do you say 'this' in Spanish?" },
  { es: "¿Dónde puedo comprar los boletos?", en: "Where can I buy tickets?" },
  { es: "Quisiera reservar una mesa, por favor.", en: "I'd like to book a table, please." },
  { es: "¿Para cuántas personas?", en: "For how many people?" },
  { es: "¿Qué recomiendas para comer?", en: "What do you recommend to eat?" },
  { es: "¿Nos trae la cuenta, por favor?", en: "Could you bring us the bill, please?" },
  { es: "Estoy perdido.", en: "I'm lost." },
  { es: "¿Cuánto se tarda en llegar?", en: "How long does it take to get there?" },
  { es: "¿Está lejos de aquí?", en: "Is it far from here?" },
  { es: "Voy a la oficina en autobús.", en: "I go to the office by bus." },
  { es: "¿Cómo estuvo tu día?", en: "How was your day?" },
  { es: "¿Qué tiempo hace hoy?", en: "What's the weather like today?" },
  { es: "Tengo ganas de una pizza.", en: "I feel like having a pizza (I have desire for a pizza)" },
  { es: "¿Prefieres té o café?", en: "Do you prefer tea or coffee?" },
  { es: "¿Puedo pagar con tarjeta?", en: "Can I pay by card?" },
  { es: "¿Ya comiste?", en: "Have you eaten already?" },
  { es: "Hablamos mañana por la mañana.", en: "We'll talk tomorrow morning." },
  { es: "Mándame tu ubicación, por favor.", en: "Send me your location, please." },
  { es: "Te envío el enlace en un rato.", en: "I'll send you the link shortly." },
  { es: "¿En qué piso vives?", en: "What floor do you live on?" },
  { es: "¿Estás libre este fin de semana?", en: "Are you free this weekend?" },
  { es: "¿Podemos vernos sobre las ocho?", en: "Can we meet around eight?" },
  { es: "Mañana tengo que levantarme temprano.", en: "I have to get up early tomorrow." },
  { es: "Estoy buscando trabajo.", en: "I'm looking for a job." },
  { es: "Aquí no tengo señal.", en: "I have no signal here." },
  { es: "¿Me mandas un mensaje cuando llegues?", en: "Will you text me when you arrive?" },
  { es: "Me duele la cabeza.", en: "My head hurts." },
  { es: "¿Puedes vigilar mi bolso?", en: "Can you watch my bag?" },
  { es: "No te preocupes, yo me encargo.", en: "Don't worry, I'll take care of it." },
  { es: "¿Te parece bien a las siete?", en: "Is seven okay for you?" },
  { es: "¿Necesitas una mano?", en: "Do you need a hand?" },
  { es: "Después del trabajo paso por tu casa.", en: "After work I'll stop by your place." },
  { es: "Pon música si quieres.", en: "Put on some music if you want." },
  { es: "Nos vemos frente a la estación.", en: "See you in front of the station." },
  { es: "Me bajo en la próxima parada.", en: "I'm getting off at the next stop." },
  { es: "¿Me recomiendas un buen restaurante?", en: "Can you recommend a good restaurant?" },
  // New additions
  { es: "¿Cuánto tiempo tardas en llegar?", en: "How long does it take you to get there?" },
  { es: "¿Te puedo invitar algo de beber?", en: "Can I buy you a drink?" },
  { es: "¿Qué te gustaría hacer?", en: "What would you like to do?" },
  { es: "¿Has visto mi teléfono?", en: "Have you seen my phone?" },
  { es: "No encuentro mis llaves.", en: "I can't find my keys." },
  { es: "Tengo que irme en cinco minutos.", en: "I have to leave in five minutes." },
  { es: "Estoy esperando a un amigo.", en: "I'm waiting for a friend." },
  { es: "¿Cuánto tiempo te quedas aquí?", en: "How long are you staying here?" },
  { es: "Es la primera vez que vengo.", en: "It's my first time here." },
  { es: "¿Me lo puedes explicar otra vez?", en: "Can you explain it to me again?" },
  { es: "No me siento muy bien.", en: "I don't feel very well." },
  { es: "Necesito descansar un poco.", en: "I need to rest a bit." },
  { es: "¿Dónde compraste esto?", en: "Where did you buy this?" },
  { es: "¿Cuánto cuesta el billete?", en: "How much is the ticket?" },
  { es: "¿Hay descuento para estudiantes?", en: "Is there a student discount?" },
  { es: "¿Aceptan efectivo?", en: "Do you accept cash?" },
  { es: "¿Dónde puedo cambiar dinero?", en: "Where can I exchange money?" },
  { es: "¿Hay una farmacia cerca?", en: "Is there a pharmacy nearby?" },
  { es: "Necesito tomar una medicina.", en: "I need to take medicine." },
  { es: "¿Tienes el horario de los autobuses?", en: "Do you have the bus schedule?" },
  { es: "¿Cuándo sale el próximo tren?", en: "When does the next train leave?" },
  { es: "¿Puedo sentarme aquí?", en: "Can I sit here?" },
  { es: "¿Está libre este asiento?", en: "Is this seat free?" },
  { es: "Disculpa, ¿puedo pasar?", en: "Excuse me, can I get through?" },
  { es: "Nunca lo he hecho antes.", en: "I've never done this before." },
  { es: "¿Cómo funciona esto?", en: "How does this work?" },
  { es: "¿Me puedes enseñar cómo se hace?", en: "Can you show me how to do it?" },
  { es: "No estoy seguro de haber entendido.", en: "I'm not sure I understood." },
  { es: "¿Podrías hablar un poco más alto?", en: "Could you speak a bit louder?" },
  { es: "La música está muy alta.", en: "The music is too loud." },
  { es: "Hace mucho calor aquí dentro.", en: "It's too hot in here." },
  { es: "¿Podemos abrir la ventana?", en: "Can we open the window?" },
  { es: "¿Tienes hambre? Pidamos algo.", en: "Are you hungry? Let's order something." },
  { es: "¿Qué quieres beber?", en: "What do you want to drink?" },
  { es: "Coge lo que quieras.", en: "Take whatever you want." },
  { es: "¿Me dejas ver el menú?", en: "Can I see the menu?" },
  { es: "Soy alérgico a...", en: "I'm allergic to..." },
  { es: "¿Este plato es picante?", en: "Is this dish spicy?" },
  { es: "¿Cuál es la especialidad de la casa?", en: "What's the house specialty?" },
  { es: "Quisiera pedir esto.", en: "I'd like to order this." },
  { es: "¿Cuánto tiempo tarda?", en: "How long will it take?" },
  { es: "¿Me puedes traer un vaso de agua?", en: "Can you bring me a glass of water?" },
  { es: "¿Está incluido en el precio?", en: "Is it included in the price?" },
  { es: "¿Tengo que reservar con anticipación?", en: "Do I need to book in advance?" },
  { es: "¿A qué hora cierran?", en: "What time do you close?" },
  { es: "¿A qué hora abren mañana?", en: "What time do you open tomorrow?" },
  { es: "¿Lo puedo probar primero?", en: "Can I try it first?" },
  { es: "¿Lo tienen en otra talla?", en: "Do you have it in another size?" },
  { es: "¿Lo puedo devolver si no me queda bien?", en: "Can I return it if it doesn't fit?" },
  { es: "¿Tienen wifi aquí?", en: "Do you have wifi here?" },
  { es: "¿Cuál es la contraseña del wifi?", en: "What's the wifi password?" }
];

export const FRENCH_PHRASES_EASY = [
  { fr: "Bonjour !", en: "Good morning!" },
  { fr: "Bonsoir !", en: "Good evening!" },
  { fr: "Bonne nuit !", en: "Good night!" },
  { fr: "Salut !", en: "Hi/Bye!" },
  { fr: "À plus tard !", en: "See you later!" },
  { fr: "À demain !", en: "See you tomorrow!" },
  { fr: "Ça va ?", en: "How's it going?" },
  { fr: "Comment ça va ?", en: "How are you?" },
  { fr: "Comment tu t'appelles ?", en: "What's your name?" },
  { fr: "Je m'appelle …", en: "My name is..." },
  { fr: "Ravi de te rencontrer.", en: "Nice to meet you." },
  { fr: "D'où viens-tu ?", en: "Where are you from?" },
  { fr: "Je viens de Paris.", en: "I'm from Paris." },
  { fr: "Tu habites où ?", en: "Where do you live?" },
  { fr: "S'il te plaît.", en: "Please." },
  { fr: "Merci !", en: "Thanks!" },
  { fr: "De rien.", en: "You're welcome." },
  { fr: "Pardon.", en: "Sorry." },
  { fr: "Un moment, s'il te plaît.", en: "One moment, please." },
  { fr: "Tu es où ?", en: "Where are you?" },
  { fr: "À quelle heure ?", en: "What time?" },
  { fr: "Il est quelle heure ?", en: "What time is it?" },
  { fr: "On y va !", en: "Let's go!" },
  { fr: "Attends !", en: "Wait!" },
  { fr: "Je ne comprends pas.", en: "I don't understand." },
  { fr: "Combien ça coûte ?", en: "How much is it?" },
  { fr: "Ça marche.", en: "It works." },
  { fr: "Super !", en: "Great!" },
  { fr: "Je ne sais pas.", en: "I don't know." },
  { fr: "Peut-être.", en: "Maybe." },
  { fr: "Un café, s'il te plaît.", en: "A coffee, please." },
  { fr: "J'ai faim.", en: "I'm hungry (I have hunger)" },
  { fr: "J'ai soif.", en: "I'm thirsty (I have thirst)" },
  { fr: "Bonne journée !", en: "Have a nice day!" },
  { fr: "Bonne chance !", en: "Good luck!" },
  { fr: "Félicitations !", en: "Congrats!" },
  { fr: "Ça ne marche pas.", en: "It doesn't work." },
  { fr: "Tout va bien.", en: "Everything's okay." },
  { fr: "Génial !", en: "Awesome!" },
  { fr: "Ça me va.", en: "Works for me." },
  { fr: "Bon appétit !", en: "Enjoy your meal!" },
  { fr: "Santé !", en: "Cheers!" },
  { fr: "Fais attention !", en: "Watch out!" },
  { fr: "Vas-y !", en: "Go for it!" },
  { fr: "Où es-tu ?", en: "Where are you?" },
  { fr: "On se retrouve là.", en: "Meet you there." },
  { fr: "À plus.", en: "See ya." },
  { fr: "À tout à l'heure.", en: "See you later." },
  { fr: "À tout de suite.", en: "Be right back." },
  // New additions
  { fr: "Parfait !", en: "Perfect!" },
  { fr: "Incroyable !", en: "Incredible!" },
  { fr: "C'est vrai ?", en: "Is it true?" },
  { fr: "Bien sûr !", en: "Of course!" },
  { fr: "Exactement !", en: "Exactly!" },
  { fr: "D'accord.", en: "Okay." },
  { fr: "Arrête !", en: "Stop!" },
  { fr: "Encore.", en: "Again." },
  { fr: "Maintenant.", en: "Now." },
  { fr: "Plus tard.", en: "Later." },
  { fr: "Aujourd'hui.", en: "Today." },
  { fr: "Demain.", en: "Tomorrow." },
  { fr: "Hier.", en: "Yesterday." },
  { fr: "Toujours.", en: "Always." },
  { fr: "Jamais.", en: "Never." },
  { fr: "À bientôt !", en: "See you soon!" },
  { fr: "Bon voyage !", en: "Have a good trip!" },
  { fr: "Bon week-end !", en: "Have a good weekend!" },
  { fr: "Quelle surprise !", en: "What a surprise!" },
  { fr: "Désolé.", en: "Sorry." },
  { fr: "Pardonne-moi.", en: "Forgive me." },
  { fr: "Pas de problème.", en: "No problem." },
  { fr: "Ce n'est rien.", en: "It's nothing." },
  { fr: "Tranquille.", en: "Relax." },
  { fr: "Pas de souci.", en: "No worries." },
  { fr: "Avec plaisir.", en: "With pleasure." },
  { fr: "Très gentil.", en: "Very kind." },
  { fr: "Tu es très gentil.", en: "You're very kind." },
  { fr: "Je suis fatigué.", en: "I'm tired." },
  { fr: "J'ai sommeil.", en: "I'm sleepy (I have sleepiness)" },
  { fr: "J'ai froid.", en: "I'm cold (I have cold)" },
  { fr: "J'ai chaud.", en: "I'm hot (I have heat)" },
  { fr: "Il fait chaud.", en: "It's hot." },
  { fr: "Il fait froid.", en: "It's cold." },
  { fr: "Il fait beau.", en: "The weather is nice." },
  { fr: "Il pleut.", en: "It's raining." },
  { fr: "Il neige.", en: "It's snowing." },
  { fr: "Il y a du soleil.", en: "It's sunny." },
  { fr: "Je reviens tout de suite.", en: "I'll be right back." },
  { fr: "Me voilà.", en: "Here I am." },
  { fr: "J'arrive !", en: "I'm coming!" },
  { fr: "Bravo !", en: "Well done!" },
  { fr: "Courage !", en: "Courage!" },
  { fr: "Chouette !", en: "Cool!" },
  { fr: "J'aime ça.", en: "I like it." },
  { fr: "J'aime pas.", en: "I don't like it." },
  { fr: "Oui.", en: "Yes." },
  { fr: "Non.", en: "No." }
];

export const FRENCH_PHRASES_MEDIUM = [
  { fr: "Quel est ton nom de famille ?", en: "What's your last name?" },
  { fr: "Tu as quel âge ?", en: "How old are you?" },
  { fr: "On se retrouve où ?", en: "Where shall we meet?" },
  { fr: "À quelle heure on se voit ?", en: "What time shall we meet?" },
  { fr: "J'arrive dans une minute.", en: "I'll be there in a minute." },
  { fr: "Je suis en retard de cinq minutes.", en: "I'm five minutes late." },
  { fr: "On peut parler plus tard ?", en: "Can we talk later?" },
  { fr: "Tu fais quoi ce soir ?", en: "What are you doing tonight?" },
  { fr: "Tu veux sortir avec moi ?", en: "Do you want to go out with me?" },
  { fr: "On se voit à l'entrée principale.", en: "See you at the main entrance." },
  { fr: "Où sont les toilettes ?", en: "Where is the bathroom?" },
  { fr: "Désolé, je ne peux pas.", en: "Sorry, I can't." },
  { fr: "Je n'ai pas bien compris.", en: "I didn't quite understand." },
  { fr: "Parle plus lentement, s'il te plaît.", en: "Speak more slowly, please." },
  { fr: "Tu peux répéter, s'il te plaît ?", en: "Can you repeat, please?" },
  { fr: "Comment on dit 'ça' en français ?", en: "How do you say 'that' in French?" },
  { fr: "Où puis-je acheter des billets ?", en: "Where can I buy tickets?" },
  { fr: "Je voudrais réserver une table, s'il vous plaît.", en: "I'd like to book a table, please." },
  { fr: "Pour combien de personnes ?", en: "For how many people?" },
  { fr: "Qu'est-ce que tu conseilles à manger ?", en: "What do you recommend to eat?" },
  { fr: "On peut avoir l'addition, s'il vous plaît ?", en: "Could we have the bill, please?" },
  { fr: "Je suis perdu.", en: "I'm lost." },
  { fr: "Ça prend combien de temps pour arriver ?", en: "How long does it take to get there?" },
  { fr: "C'est loin d'ici ?", en: "Is it far from here?" },
  { fr: "Je vais au travail en bus.", en: "I go to work by bus." },
  { fr: "Comment s'est passée ta journée ?", en: "How was your day?" },
  { fr: "Quel temps fait-il aujourd'hui ?", en: "What's the weather like today?" },
  { fr: "J'ai envie d'une pizza.", en: "I feel like having a pizza (I have desire for a pizza)" },
  { fr: "Tu préfères le thé ou le café ?", en: "Do you prefer tea or coffee?" },
  { fr: "Je peux payer par carte ?", en: "Can I pay by card?" },
  { fr: "Tu as déjà mangé ?", en: "Have you eaten already?" },
  { fr: "On s'appelle demain matin.", en: "We'll talk tomorrow morning." },
  { fr: "Envoie-moi ta position, s'il te plaît.", en: "Send me your location, please." },
  { fr: "Je t'envoie le lien dans un instant.", en: "I'll send you the link shortly." },
  { fr: "Tu habites à quel étage ?", en: "What floor do you live on?" },
  { fr: "Tu es libre ce week-end ?", en: "Are you free this weekend?" },
  { fr: "On peut se voir vers huit heures ?", en: "Can we meet around eight?" },
  { fr: "Je dois me lever tôt demain.", en: "I have to get up early tomorrow." },
  { fr: "Je cherche du travail.", en: "I'm looking for a job." },
  { fr: "Je n'ai pas de réseau ici.", en: "I have no signal here." },
  { fr: "Tu m'envoies un message quand tu arrives ?", en: "Will you text me when you arrive?" },
  { fr: "J'ai mal à la tête.", en: "My head hurts." },
  { fr: "Tu peux surveiller mon sac ?", en: "Can you watch my bag?" },
  { fr: "T'inquiète pas, je m'en occupe.", en: "Don't worry, I'll take care of it." },
  { fr: "Sept heures, ça te va ?", en: "Is seven okay for you?" },
  { fr: "Tu as besoin d'un coup de main ?", en: "Do you need a hand?" },
  { fr: "Après le travail je passe chez toi.", en: "After work I'll stop by your place." },
  { fr: "Mets un peu de musique.", en: "Put on some music." },
  { fr: "On se retrouve devant la gare.", en: "See you in front of the station." },
  { fr: "Je descends au prochain arrêt.", en: "I'm getting off at the next stop." },
  { fr: "Tu peux me recommander un bon resto ?", en: "Can you recommend a good restaurant?" },
  // New additions
  { fr: "Ça te prend combien de temps pour arriver ?", en: "How long does it take you to get there?" },
  { fr: "Je peux t'offrir quelque chose à boire ?", en: "Can I buy you a drink?" },
  { fr: "Qu'est-ce que tu aimerais faire ?", en: "What would you like to do?" },
  { fr: "Tu as vu mon téléphone ?", en: "Have you seen my phone?" },
  { fr: "Je ne trouve pas mes clés.", en: "I can't find my keys." },
  { fr: "Je dois partir dans cinq minutes.", en: "I have to leave in five minutes." },
  { fr: "J'attends un ami.", en: "I'm waiting for a friend." },
  { fr: "Tu restes combien de temps ici ?", en: "How long are you staying here?" },
  { fr: "C'est la première fois que je viens.", en: "It's my first time here." },
  { fr: "Tu peux me l'expliquer encore ?", en: "Can you explain it to me again?" },
  { fr: "Je ne me sens pas très bien.", en: "I don't feel very well." },
  { fr: "J'ai besoin de me reposer un peu.", en: "I need to rest a bit (I have need to rest a bit)" },
  { fr: "Tu as acheté ça où ?", en: "Where did you buy this?" },
  { fr: "C'est combien le billet ?", en: "How much is the ticket?" },
  { fr: "Il y a une réduction pour étudiants ?", en: "Is there a student discount?" },
  { fr: "Vous acceptez les espèces ?", en: "Do you accept cash?" },
  { fr: "Où puis-je changer de l'argent ?", en: "Where can I exchange money?" },
  { fr: "Il y a une pharmacie près d'ici ?", en: "Is there a pharmacy nearby?" },
  { fr: "Je dois prendre un médicament.", en: "I need to take medicine." },
  { fr: "Tu as les horaires de bus ?", en: "Do you have the bus schedule?" },
  { fr: "Le prochain train part quand ?", en: "When does the next train leave?" },
  { fr: "Je peux m'asseoir ici ?", en: "Can I sit here?" },
  { fr: "Cette place est libre ?", en: "Is this seat free?" },
  { fr: "Excusez-moi, je peux passer ?", en: "Excuse me, can I get through?" },
  { fr: "Je ne l'ai jamais fait avant.", en: "I've never done this before." },
  { fr: "Ça marche comment ?", en: "How does this work?" },
  { fr: "Tu peux me montrer comment faire ?", en: "Can you show me how to do it?" },
  { fr: "Je ne suis pas sûr d'avoir compris.", en: "I'm not sure I understood." },
  { fr: "Tu pourrais parler un peu plus fort ?", en: "Could you speak a bit louder?" },
  { fr: "La musique est trop forte.", en: "The music is too loud." },
  { fr: "Il fait trop chaud ici.", en: "It's too hot in here." },
  { fr: "On peut ouvrir la fenêtre ?", en: "Can we open the window?" },
  { fr: "Tu as faim ? On commande quelque chose.", en: "Are you hungry? Let's order something." },
  { fr: "Qu'est-ce que tu veux boire ?", en: "What do you want to drink?" },
  { fr: "Prends ce que tu veux.", en: "Take whatever you want." },
  { fr: "Je peux voir le menu ?", en: "Can I see the menu?" },
  { fr: "Je suis allergique à...", en: "I'm allergic to..." },
  { fr: "Ce plat est épicé ?", en: "Is this dish spicy?" },
  { fr: "C'est quoi la spécialité de la maison ?", en: "What's the house specialty?" },
  { fr: "Je voudrais commander ça.", en: "I'd like to order this." },
  { fr: "Ça prend combien de temps ?", en: "How long will it take?" },
  { fr: "Je peux avoir un verre d'eau ?", en: "Can I have a glass of water?" },
  { fr: "C'est inclus dans le prix ?", en: "Is it included in the price?" },
  { fr: "Il faut réserver à l'avance ?", en: "Do I need to book in advance?" },
  { fr: "Vous fermez à quelle heure ?", en: "What time do you close?" },
  { fr: "Vous ouvrez à quelle heure demain ?", en: "What time do you open tomorrow?" },
  { fr: "Je peux l'essayer d'abord ?", en: "Can I try it first?" },
  { fr: "Vous l'avez dans une autre taille ?", en: "Do you have it in another size?" },
  { fr: "Je peux le rendre s'il ne va pas ?", en: "Can I return it if it doesn't fit?" },
  { fr: "Vous avez le wifi ici ?", en: "Do you have wifi here?" },
  { fr: "C'est quoi le mot de passe du wifi ?", en: "What's the wifi password?" }
];

export const JAPANESE_PHRASES_EASY = [
  { ja: "こんにちは (Konnichiwa)", en: "Hello." },
  { ja: "おはようございます (Ohayou gozaimasu)", en: "Good morning." },
  { ja: "こんばんは (Konbanwa)", en: "Good evening." },
  { ja: "おやすみなさい (Oyasuminasai)", en: "Good night." },
  { ja: "やあ (Yā)", en: "Hi." },
  { ja: "またね (Mata ne)", en: "See you." },
  { ja: "また明日 (Mata ashita)", en: "See you tomorrow." },
  { ja: "また後で (Mata ato de)", en: "See you later." },
  { ja: "元気ですか？ (Genki desu ka?)", en: "How are you?" },
  { ja: "元気です (Genki desu)", en: "I'm fine." },
  { ja: "ありがとうございます (Arigatou gozaimasu)", en: "Thank you very much." },
  { ja: "ありがとう (Arigatou)", en: "Thanks." },
  { ja: "どういたしまして (Dou itashimashite)", en: "You're welcome." },
  { ja: "すみません (Sumimasen)", en: "Excuse me." },
  { ja: "ごめんなさい (Gomen nasai)", en: "I'm sorry." },
  { ja: "大丈夫です (Daijoubu desu)", en: "It's okay." },
  { ja: "少々お待ちください (Shoushou omachi kudasai)", en: "One moment, please." },
  { ja: "ちょっと待って (Chotto matte)", en: "Wait a sec." },
  { ja: "どこにいますか？ (Doko ni imasu ka?)", en: "Where are you?" },
  { ja: "何時に？ (Nanji ni?)", en: "At what time?" },
  { ja: "今何時ですか？ (Ima nanji desu ka?)", en: "What time is it?" },
  { ja: "行きましょう！ (Ikimashou!)", en: "Let's go!" },
  { ja: "わかりました (Wakarimashita)", en: "Got it." },
  { ja: "わかりません (Wakarimasen)", en: "I don't understand." },
  { ja: "いくらですか？ (Ikura desu ka?)", en: "How much is it?" },
  { ja: "これはいくら？ (Kore wa ikura?)", en: "How much is this?" },
  { ja: "これが好きです (Kore ga suki desu)", en: "I like this." },
  { ja: "お願いします (Onegaishimasu)", en: "Please." },
  { ja: "いいですよ (Ii desu yo)", en: "Sure." },
  { ja: "知りません (Shirimasen)", en: "I don't know." },
  { ja: "了解です (Ryoukai desu)", en: "Roger that." },
  { ja: "水をください (Mizu o kudasai)", en: "Water, please." },
  { ja: "がんばって！ (Ganbatte!)", en: "Good luck!" },
  { ja: "おめでとう！ (Omedetou!)", en: "Congratulations!" },
  { ja: "すごい！ (Sugoi!)", en: "Awesome!" },
  { ja: "最高！ (Saikou!)", en: "The best!" },
  { ja: "いいね (Ii ne)", en: "Nice." },
  { ja: "なるほど (Naruhodo)", en: "I see." },
  { ja: "ちょうどいい (Choudo ii)", en: "Just right." },
  { ja: "連絡します (Renraku shimasu)", en: "I'll contact you." },
  { ja: "電話します (Denwa shimasu)", en: "I'll call you." },
  { ja: "できます (Dekimasu)", en: "I can." },
  { ja: "できません (Dekimasen)", en: "I can't." },
  { ja: "助かります (Tasukarimasu)", en: "That helps." },
  { ja: "覚えています (Oboete imasu)", en: "I remember." },
  { ja: "開いていますか？ (Aite imasu ka?)", en: "Are you open?" },
  { ja: "閉まっていますか？ (Shimatte imasu ka?)", en: "Are you closed?" },
  { ja: "よろしくお願いします (Yoroshiku onegaishimasu)", en: "Nice to meet you." },
  // New additions
  { ja: "はい (Hai)", en: "Yes." },
  { ja: "いいえ (Iie)", en: "No." },
  { ja: "お腹がすきました (Onaka ga sukimashita)", en: "I'm hungry." },
  { ja: "喉が渇きました (Nodo ga kawakimashita)", en: "I'm thirsty." },
  { ja: "楽しい (Tanoshii)", en: "Fun." },
  { ja: "嬉しい (Ureshii)", en: "Happy." },
  { ja: "かわいい (Kawaii)", en: "Cute." },
  { ja: "きれい (Kirei)", en: "Beautiful." },
  { ja: "美味しい (Oishii)", en: "Delicious." },
  { ja: "おいしかった (Oishikatta)", en: "It was delicious." },
  { ja: "いただきます (Itadakimasu)", en: "Let's eat." },
  { ja: "ごちそうさまでした (Gochisousama deshita)", en: "Thank you for the meal." },
  { ja: "乾杯！ (Kanpai!)", en: "Cheers!" },
  { ja: "本当ですか？ (Hontou desu ka?)", en: "Really?" },
  { ja: "本当に！ (Hontou ni!)", en: "Really!" },
  { ja: "そうですか (Sou desu ka)", en: "Is that so?" },
  { ja: "そうです (Sou desu)", en: "That's right." },
  { ja: "違います (Chigaimasu)", en: "That's wrong." },
  { ja: "多分 (Tabun)", en: "Maybe." },
  { ja: "もちろん (Mochiron)", en: "Of course." },
  { ja: "絶対 (Zettai)", en: "Absolutely." },
  { ja: "頑張ります (Ganbarimasu)", en: "I'll do my best." },
  { ja: "いってきます (Itte kimasu)", en: "I'm leaving." },
  { ja: "いってらっしゃい (Itte rasshai)", en: "Take care." },
  { ja: "ただいま (Tadaima)", en: "I'm home." },
  { ja: "お帰りなさい (Okaeri nasai)", en: "Welcome home." },
  { ja: "久しぶり (Hisashiburi)", en: "Long time no see." },
  { ja: "気をつけて (Ki o tsukete)", en: "Be careful." },
  { ja: "今すぐ (Ima sugu)", en: "Right now." },
  { ja: "後で (Ato de)", en: "Later." },
  { ja: "今日 (Kyou)", en: "Today." },
  { ja: "明日 (Ashita)", en: "Tomorrow." },
  { ja: "昨日 (Kinou)", en: "Yesterday." },
  { ja: "いつも (Itsumo)", en: "Always." },
  { ja: "全然 (Zenzen)", en: "Not at all." },
  { ja: "ちょっと (Chotto)", en: "A little." },
  { ja: "たくさん (Takusan)", en: "A lot." },
  { ja: "とても (Totemo)", en: "Very." },
  { ja: "本当に (Hontou ni)", en: "Really." },
  { ja: "少し (Sukoshi)", en: "A bit." },
  { ja: "全部 (Zenbu)", en: "Everything." },
  { ja: "何も (Nani mo)", en: "Nothing." },
  { ja: "誰か (Dare ka)", en: "Someone." },
  { ja: "誰も (Dare mo)", en: "No one." },
  { ja: "ここ (Koko)", en: "Here." },
  { ja: "そこ (Soko)", en: "There." },
  { ja: "あそこ (Asoko)", en: "Over there." },
  { ja: "どこ？ (Doko?)", en: "Where?" }
];

export const JAPANESE_PHRASES_MEDIUM = [
  { ja: "すぐ戻ります (Sugu modorimasu)", en: "Be right back." },
  { ja: "お名前は何ですか？ (Onamae wa nan desu ka?)", en: "What is your name?" },
  { ja: "どこに住んでいますか？ (Doko ni sundeimasu ka?)", en: "Where do you live?" },
  { ja: "ご出身はどちらですか？ (Goshusshin wa dochira desu ka?)", en: "Where are you from?" },
  { ja: "これは何ですか？ (Kore wa nan desu ka?)", en: "What is this?" },
  { ja: "どういう意味ですか？ (Dou iu imi desu ka?)", en: "What does it mean?" },
  { ja: "英語を話せますか？ (Eigo o hanasemasu ka?)", en: "Can you speak English?" },
  { ja: "もう一度お願いします (Mou ichido onegaishimasu)", en: "One more time, please." },
  { ja: "ゆっくり話してください (Yukkuri hanashite kudasai)", en: "Please speak slowly." },
  { ja: "写真を撮ってもいいですか？ (Shashin o totte mo ii desu ka?)", en: "Can I take a photo?" },
  { ja: "おすすめは何ですか？ (Osusume wa nan desu ka?)", en: "What do you recommend?" },
  { ja: "駅はどこですか？ (Eki wa doko desu ka?)", en: "Where is the station?" },
  { ja: "トイレはどこですか？ (Toire wa doko desu ka?)", en: "Where is the restroom?" },
  { ja: "ここに座ってもいいですか？ (Koko ni suwatte mo ii desu ka?)", en: "May I sit here?" },
  { ja: "一緒に行きませんか？ (Issho ni ikimasen ka?)", en: "Shall we go together?" },
  { ja: "ちょっと手伝ってくれますか？ (Chotto tetsudatte kuremasu ka?)", en: "Can you help me a little?" },
  { ja: "時間がありますか？ (Jikan ga arimasu ka?)", en: "Do you have time?" },
  { ja: "手伝いましょうか？ (Tetsudaimashou ka?)", en: "Shall I help you?" },
  { ja: "どこで買えますか？ (Doko de kaemasu ka?)", en: "Where can I buy it?" },
  { ja: "カードで払えますか？ (Kaado de haraemasu ka?)", en: "Can I pay by card?" },
  { ja: "領収書をください (Ryoushuusho o kudasai)", en: "Please give me a receipt." },
  { ja: "予約をしたいです (Yoyaku o shitai desu)", en: "I'd like to make a reservation." },
  { ja: "何人ですか？ (Nan-nin desu ka?)", en: "For how many people?" },
  { ja: "おすすめ料理は何ですか？ (Osusume ryouri wa nan desu ka?)", en: "What dish do you recommend?" },
  { ja: "お会計お願いします (Okaikei onegaishimasu)", en: "The check, please." },
  { ja: "バス停はどこですか？ (Basutei wa doko desu ka?)", en: "Where is the bus stop?" },
  { ja: "空港までどのくらいかかりますか？ (Kuukou made dono kurai kakarimasu ka?)", en: "How long to the airport?" },
  { ja: "近いですか？ (Chikai desu ka?)", en: "Is it nearby?" },
  { ja: "ここから遠いですか？ (Koko kara tooi desu ka?)", en: "Is it far from here?" },
  { ja: "電車で行けますか？ (Densha de ikemasu ka?)", en: "Can I go by train?" },
  { ja: "今日は何日ですか？ (Kyou wa nannichi desu ka?)", en: "What's the date today?" },
  { ja: "今日は何曜日ですか？ (Kyou wa nanyoubi desu ka?)", en: "What day is it today?" },
  { ja: "天気はどうですか？ (Tenki wa dou desu ka?)", en: "How's the weather?" },
  { ja: "今日は暑いですね (Kyou wa atsui desu ne)", en: "It's hot today." },
  { ja: "今日は寒いですね (Kyou wa samui desu ne)", en: "It's cold today." },
  { ja: "眠いです (Nemui desu)", en: "I'm sleepy." },
  { ja: "疲れました (Tsukaremashita)", en: "I'm tired." },
  { ja: "お腹がいっぱいです (Onaka ga ippai desu)", en: "I'm full." },
  { ja: "お腹がすいています (Onaka ga suite imasu)", en: "I'm hungry." },
  { ja: "のどが渇きました (Nodo ga kawakimashita)", en: "I'm thirsty." },
  { ja: "気をつけて！ (Ki o tsukete!)", en: "Take care!" },
  { ja: "大丈夫ですか？ (Daijoubu desu ka?)", en: "Are you okay?" },
  { ja: "何が起きていますか？ (Nani ga okite imasu ka?)", en: "What's happening?" },
  { ja: "一緒に写真を撮りましょう (Issho ni shashin o torimashou)", en: "Let's take a photo together." },
  { ja: "後で連絡します (Ato de renraku shimasu)", en: "I'll contact you later." },
  { ja: "また会いましょう (Mata aimashou)", en: "Let's meet again." },
  { ja: "お元気で！ (Ogenki de!)", en: "Take care of yourself!" },
  { ja: "頑張ってください (Ganbatte kudasai)", en: "Please do your best." },
  { ja: "気にしないでください (Ki ni shinaide kudasai)", en: "Don't worry about it." },
  // New additions
  { ja: "どのくらい時間がかかりますか？ (Dono kurai jikan ga kakarimasu ka?)", en: "How long does it take?" },
  { ja: "何か飲み物をどうですか？ (Nanika nomimono o dou desu ka?)", en: "Would you like something to drink?" },
  { ja: "何をしたいですか？ (Nani o shitai desu ka?)", en: "What do you want to do?" },
  { ja: "携帯を見ましたか？ (Keitai o mimashita ka?)", en: "Have you seen my phone?" },
  { ja: "鍵が見つかりません (Kagi ga mitsukarimasen)", en: "I can't find my keys." },
  { ja: "5分後に出なければなりません (Gofun-go ni denakereba narimasen)", en: "I have to leave in five minutes." },
  { ja: "友達を待っています (Tomodachi o matte imasu)", en: "I'm waiting for a friend." },
  { ja: "どのくらいここにいますか？ (Dono kurai koko ni imasu ka?)", en: "How long are you staying here?" },
  { ja: "初めて来ました (Hajimete kimashita)", en: "It's my first time here." },
  { ja: "もう一度説明してくれますか？ (Mou ichido setsumei shite kuremasu ka?)", en: "Can you explain it to me again?" },
  { ja: "体調が悪いです (Taichou ga warui desu)", en: "I don't feel well." },
  { ja: "少し休みたいです (Sukoshi yasumitai desu)", en: "I want to rest a bit." },
  { ja: "これはどこで買いましたか？ (Kore wa doko de kaimashita ka?)", en: "Where did you buy this?" },
  { ja: "切符はいくらですか？ (Kippu wa ikura desu ka?)", en: "How much is the ticket?" },
  { ja: "学生割引はありますか？ (Gakusei waribiki wa arimasu ka?)", en: "Is there a student discount?" },
  { ja: "現金で払えますか？ (Genkin de haraemasu ka?)", en: "Can I pay with cash?" },
  { ja: "どこで両替できますか？ (Doko de ryougae dekimasu ka?)", en: "Where can I exchange money?" },
  { ja: "近くに薬局はありますか？ (Chikaku ni yakkyoku wa arimasu ka?)", en: "Is there a pharmacy nearby?" },
  { ja: "薬を飲む必要があります (Kusuri o nomu hitsuyou ga arimasu)", en: "I need to take medicine." },
  { ja: "バスの時刻表はありますか？ (Basu no jikokuhyou wa arimasu ka?)", en: "Do you have a bus schedule?" },
  { ja: "次の電車はいつ出ますか？ (Tsugi no densha wa itsu demasu ka?)", en: "When does the next train leave?" },
  { ja: "ここに座ってもいいですか？ (Koko ni suwatte mo ii desu ka?)", en: "Can I sit here?" },
  { ja: "この席は空いていますか？ (Kono seki wa aite imasu ka?)", en: "Is this seat free?" },
  { ja: "すみません、通してください (Sumimasen, tooshite kudasai)", en: "Excuse me, can I get through?" },
  { ja: "これは初めてです (Kore wa hajimete desu)", en: "This is my first time." },
  { ja: "これはどう使いますか？ (Kore wa dou tsukaimasu ka?)", en: "How do you use this?" },
  { ja: "やり方を教えてくれますか？ (Yarikata o oshiete kuremasu ka?)", en: "Can you show me how to do it?" },
  { ja: "理解できたか自信がありません (Rikai dekita ka jishin ga arimasen)", en: "I'm not sure I understood." },
  { ja: "もう少し大きい声で話してくれますか？ (Mou sukoshi ookii koe de hanashite kuremasu ka?)", en: "Could you speak a bit louder?" },
  { ja: "音楽が大きすぎます (Ongaku ga ookisugimasu)", en: "The music is too loud." },
  { ja: "ここは暑すぎます (Koko wa atsusugimasu)", en: "It's too hot in here." },
  { ja: "窓を開けてもいいですか？ (Mado o akete mo ii desu ka?)", en: "Can we open the window?" },
  { ja: "お腹がすいていますか？何か注文しましょう (Onaka ga suite imasu ka? Nanika chuumon shimashou)", en: "Are you hungry? Let's order something." },
  { ja: "何を飲みたいですか？ (Nani o nomitai desu ka?)", en: "What do you want to drink?" },
  { ja: "好きなものを取ってください (Suki na mono o totte kudasai)", en: "Take whatever you want." },
  { ja: "メニューを見せてください (Menyuu o misete kudasai)", en: "Please show me the menu." },
  { ja: "アレルギーがあります (Arerugii ga arimasu)", en: "I have allergies." },
  { ja: "この料理は辛いですか？ (Kono ryouri wa karai desu ka?)", en: "Is this dish spicy?" },
  { ja: "おすすめの料理は何ですか？ (Osusume no ryouri wa nan desu ka?)", en: "What's the recommended dish?" },
  { ja: "これを注文したいです (Kore o chuumon shitai desu)", en: "I'd like to order this." },
  { ja: "どのくらい時間がかかりますか？ (Dono kurai jikan ga kakarimasu ka?)", en: "How long will it take?" },
  { ja: "水を一杯ください (Mizu o ippai kudasai)", en: "Can I have a glass of water?" },
  { ja: "値段に含まれていますか？ (Nedan ni fukumarete imasu ka?)", en: "Is it included in the price?" },
  { ja: "事前に予約が必要ですか？ (Jizen ni yoyaku ga hitsuyou desu ka?)", en: "Do I need to book in advance?" },
  { ja: "何時に閉まりますか？ (Nanji ni shimarimasu ka?)", en: "What time do you close?" },
  { ja: "明日は何時に開きますか？ (Ashita wa nanji ni akimasu ka?)", en: "What time do you open tomorrow?" },
  { ja: "試してもいいですか？ (Tameshite mo ii desu ka?)", en: "Can I try it?" },
  { ja: "他のサイズはありますか？ (Hoka no saizu wa arimasu ka?)", en: "Do you have other sizes?" },
  { ja: "返品できますか？ (Henpin dekimasu ka?)", en: "Can I return it?" },
  { ja: "WiFiはありますか？ (WiFi wa arimasu ka?)", en: "Do you have WiFi?" },
  { ja: "WiFiのパスワードは何ですか？ (WiFi no pasuwaado wa nan desu ka?)", en: "What's the WiFi password?" }
];



let lastItalianEasyIdx = -1;
let lastItalianMediumIdx = -1;
let lastSpanishEasyIdx = -1;
let lastSpanishMediumIdx = -1;
let lastFrenchEasyIdx = -1;
let lastFrenchMediumIdx = -1;
let lastJapaneseEasyIdx = -1;
let lastJapaneseMediumIdx = -1;

export function randomPhraseNoRepeat(language = 'italian', difficulty = 'easy') {
  if (language === 'spanish') {
    if (difficulty === 'medium') {
      if (SPANISH_PHRASES_MEDIUM.length === 0) return { es: "¡Hola!", en: "Hello!" };
      let idx;
      do { idx = Math.floor(Math.random() * SPANISH_PHRASES_MEDIUM.length); }
      while (SPANISH_PHRASES_MEDIUM.length > 1 && idx === lastSpanishMediumIdx);
      lastSpanishMediumIdx = idx;
      return SPANISH_PHRASES_MEDIUM[idx];
    } else {
      if (SPANISH_PHRASES_EASY.length === 0) return { es: "¡Hola!", en: "Hello!" };
      let idx;
      do { idx = Math.floor(Math.random() * SPANISH_PHRASES_EASY.length); }
      while (SPANISH_PHRASES_EASY.length > 1 && idx === lastSpanishEasyIdx);
      lastSpanishEasyIdx = idx;
      return SPANISH_PHRASES_EASY[idx];
    }
  } else if (language === 'french') {
    if (difficulty === 'medium') {
      if (FRENCH_PHRASES_MEDIUM.length === 0) return { fr: "Bonjour!", en: "Hello!" };
      let idx;
      do { idx = Math.floor(Math.random() * FRENCH_PHRASES_MEDIUM.length); }
      while (FRENCH_PHRASES_MEDIUM.length > 1 && idx === lastFrenchMediumIdx);
      lastFrenchMediumIdx = idx;
      return FRENCH_PHRASES_MEDIUM[idx];
    } else {
      if (FRENCH_PHRASES_EASY.length === 0) return { fr: "Bonjour!", en: "Hello!" };
      let idx;
      do { idx = Math.floor(Math.random() * FRENCH_PHRASES_EASY.length); }
      while (FRENCH_PHRASES_EASY.length > 1 && idx === lastFrenchEasyIdx);
      lastFrenchEasyIdx = idx;
      return FRENCH_PHRASES_EASY[idx];
    }
  } else if (language === 'japanese') {
    if (difficulty === 'medium') {
      if (JAPANESE_PHRASES_MEDIUM.length === 0) return { ja: "こんにちは！", en: "Hello!" };
      let idx;
      do { idx = Math.floor(Math.random() * JAPANESE_PHRASES_MEDIUM.length); }
      while (JAPANESE_PHRASES_MEDIUM.length > 1 && idx === lastJapaneseMediumIdx);
      lastJapaneseMediumIdx = idx;
      return JAPANESE_PHRASES_MEDIUM[idx];
    } else {
      if (JAPANESE_PHRASES_EASY.length === 0) return { ja: "こんにちは！", en: "Hello!" };
      let idx;
      do { idx = Math.floor(Math.random() * JAPANESE_PHRASES_EASY.length); }
      while (JAPANESE_PHRASES_EASY.length > 1 && idx === lastJapaneseEasyIdx);
      lastJapaneseEasyIdx = idx;
      return JAPANESE_PHRASES_EASY[idx];
    }
  } else {
    if (difficulty === 'medium') {
      if (ITALIAN_PHRASES_MEDIUM.length === 0) return { it: "Ciao!", en: "Hi!" };
      let idx;
      do { idx = Math.floor(Math.random() * ITALIAN_PHRASES_MEDIUM.length); }
      while (ITALIAN_PHRASES_MEDIUM.length > 1 && idx === lastItalianMediumIdx);
      lastItalianMediumIdx = idx;
      return ITALIAN_PHRASES_MEDIUM[idx];
    } else {
      if (ITALIAN_PHRASES_EASY.length === 0) return { it: "Ciao!", en: "Hi!" };
      let idx;
      do { idx = Math.floor(Math.random() * ITALIAN_PHRASES_EASY.length); }
      while (ITALIAN_PHRASES_EASY.length > 1 && idx === lastItalianEasyIdx);
      lastItalianEasyIdx = idx;
      return ITALIAN_PHRASES_EASY[idx];
    }
  }
}
