name: Daily Web Push
on:
  schedule:
    - cron: "0 7,10,13,16 * * *"   # CEST (UTC+2) -> 09/12/15/18 Rome
    - cron: "0 8,11,14,17 * * *"   # CET  (UTC+1) -> 09/12/15/18 Rome
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Gate to Rome hours only
        id: gate
        run: |
          HOUR=$(TZ=Europe/Rome date +%H)
          if [[ "$HOUR" == "09" || "$HOUR" == "12" || "$HOUR" == "15" || "$HOUR" == "18" ]]; then
            echo "OK=true" >> $GITHUB_OUTPUT
          else
            echo "OK=false" >> $GITHUB_OUTPUT
          fi
      - name: Call broadcast securely
        if: steps.gate.outputs.OK == 'true'
        run: |
          curl -sS -X POST "$PUBLIC_URL/admin/broadcast" \
            -H "X-Admin-Key: $ADMIN_KEY" \
            --max-time 20 --retry 3 --retry-delay 5 --fail
        env:
          PUBLIC_URL: ${{ secrets.PUBLIC_URL }}
          ADMIN_KEY: ${{ secrets.ADMIN_KEY }}
